import "server-only";
import {DatabaseSync} from "node:sqlite";
import {mkdirSync} from "node:fs";
import {join} from "node:path";
import {randomUUID} from "node:crypto";
import{SUBSCRIPTION_PLANS,getPlan}from"./subscription-plans";
import{addOneYear,effectiveStatus,type SubscriptionStatus}from"./subscription";

export type DbUser={id:string;email:string;name:string;role:string;institutionId:string};
export type FeeStatus="Paid"|"Partially Paid"|"Pending"|"Overdue";
export type DbStudent={id:string;name:string;admission:string;gender:string;dateOfBirth:string;className:string;section:string;grade:string;rollNumber:string;parent:string;parentPhone:string;parentEmail:string;address:string;admissionDate:string;attendance:number;fee:FeeStatus;totalFee:number;paidFee:number;pendingFee:number;status:string;createdAt:string};
export type DbTeacher={id:string;name:string;employeeId:string;email:string;phone:string;department:string;subject:string;classes:string;joiningDate:string;salary:number;status:string;createdAt:string};
export type DbClass={id:string;name:string;section:string;teacher:string;academicYear:string;capacity:number;currentStudents:number;status:string};
export type DbPayment={id:string;feeId:string;studentId:string;studentName:string;admission:string;className:string;section:string;invoiceNumber:string;receiptNumber:string;amount:number;method:string;transactionId:string;paymentDate:string;status:string;notes:string;previouslyPaid:number;totalPaid:number;remainingBalance:number;createdAt:string};

const dataDir=join(process.cwd(),"data");mkdirSync(dataDir,{recursive:true});
const db=new DatabaseSync(join(dataDir,"eduledger.db"));
db.exec("PRAGMA busy_timeout=30000; PRAGMA foreign_keys=ON;");
db.exec("PRAGMA journal_mode=WAL;");
db.exec(`
CREATE TABLE IF NOT EXISTS institutions(id TEXT PRIMARY KEY,name TEXT NOT NULL,created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS users(id TEXT PRIMARY KEY,email TEXT NOT NULL UNIQUE,name TEXT NOT NULL,password_hash TEXT NOT NULL,role TEXT NOT NULL,institution_id TEXT NOT NULL REFERENCES institutions(id),created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS sessions(token TEXT PRIMARY KEY,user_id TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,expires_at TEXT NOT NULL,created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS students(id TEXT PRIMARY KEY,institution_id TEXT NOT NULL REFERENCES institutions(id),name TEXT NOT NULL,admission TEXT NOT NULL UNIQUE,grade TEXT NOT NULL,parent TEXT NOT NULL,attendance INTEGER NOT NULL DEFAULT 100,fee TEXT NOT NULL DEFAULT 'Pending',created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS module_records(id TEXT PRIMARY KEY,institution_id TEXT NOT NULL,module TEXT NOT NULL,data TEXT NOT NULL,created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS teachers(id TEXT PRIMARY KEY,institution_id TEXT NOT NULL REFERENCES institutions(id),name TEXT NOT NULL,employee_id TEXT NOT NULL,email TEXT NOT NULL DEFAULT '',phone TEXT NOT NULL DEFAULT '',department TEXT NOT NULL DEFAULT '',subject TEXT NOT NULL DEFAULT '',assigned_classes TEXT NOT NULL DEFAULT '',joining_date TEXT NOT NULL,salary REAL NOT NULL DEFAULT 0,status TEXT NOT NULL DEFAULT 'Active',created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,UNIQUE(institution_id,employee_id));
CREATE TABLE IF NOT EXISTS classes(id TEXT PRIMARY KEY,institution_id TEXT NOT NULL REFERENCES institutions(id),name TEXT NOT NULL,section TEXT NOT NULL,teacher TEXT NOT NULL DEFAULT '',academic_year TEXT NOT NULL,capacity INTEGER NOT NULL DEFAULT 40,status TEXT NOT NULL DEFAULT 'Active',created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,UNIQUE(institution_id,name,section,academic_year));
CREATE TABLE IF NOT EXISTS attendance(id TEXT PRIMARY KEY,institution_id TEXT NOT NULL REFERENCES institutions(id),student_id TEXT NOT NULL REFERENCES students(id) ON DELETE CASCADE,date TEXT NOT NULL,status TEXT NOT NULL CHECK(status IN ('Present','Absent','Late','Leave')),remarks TEXT NOT NULL DEFAULT '',marked_by TEXT NOT NULL,created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,UNIQUE(student_id,date));
CREATE TABLE IF NOT EXISTS fees(id TEXT PRIMARY KEY,institution_id TEXT NOT NULL REFERENCES institutions(id),student_id TEXT NOT NULL REFERENCES students(id) ON DELETE CASCADE,invoice_number TEXT NOT NULL UNIQUE,fee_type TEXT NOT NULL DEFAULT 'Annual Fee',academic_year TEXT NOT NULL,total_amount REAL NOT NULL CHECK(total_amount>=0),discount REAL NOT NULL DEFAULT 0,final_amount REAL NOT NULL CHECK(final_amount>=0),paid_amount REAL NOT NULL DEFAULT 0,pending_amount REAL NOT NULL CHECK(pending_amount>=0),due_date TEXT NOT NULL,status TEXT NOT NULL,created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS payments(id TEXT PRIMARY KEY,institution_id TEXT NOT NULL REFERENCES institutions(id),student_id TEXT NOT NULL REFERENCES students(id),fee_id TEXT NOT NULL REFERENCES fees(id),receipt_number TEXT NOT NULL UNIQUE,amount REAL NOT NULL CHECK(amount>0),payment_method TEXT NOT NULL,transaction_id TEXT NOT NULL DEFAULT '',payment_date TEXT NOT NULL,status TEXT NOT NULL DEFAULT 'Success',notes TEXT NOT NULL DEFAULT '',created_by TEXT NOT NULL REFERENCES users(id),created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS receipts(id TEXT PRIMARY KEY,institution_id TEXT NOT NULL REFERENCES institutions(id),receipt_number TEXT NOT NULL UNIQUE,student_id TEXT NOT NULL REFERENCES students(id),payment_id TEXT NOT NULL UNIQUE REFERENCES payments(id),invoice_number TEXT NOT NULL,amount REAL NOT NULL,payment_method TEXT NOT NULL,transaction_id TEXT NOT NULL DEFAULT '',issued_date TEXT NOT NULL,status TEXT NOT NULL DEFAULT 'Issued',created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS activities(id TEXT PRIMARY KEY,institution_id TEXT NOT NULL REFERENCES institutions(id),type TEXT NOT NULL,title TEXT NOT NULL,description TEXT NOT NULL,student_id TEXT,payment_id TEXT,amount REAL,timestamp TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,status TEXT NOT NULL DEFAULT 'Success');
CREATE TABLE IF NOT EXISTS notifications(id TEXT PRIMARY KEY,institution_id TEXT NOT NULL REFERENCES institutions(id),user_id TEXT,type TEXT NOT NULL,title TEXT NOT NULL,description TEXT NOT NULL DEFAULT '',read_at TEXT,created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS settings(institution_id TEXT PRIMARY KEY REFERENCES institutions(id),academic_year TEXT NOT NULL DEFAULT '2026-2027',school_address TEXT NOT NULL DEFAULT '',school_phone TEXT NOT NULL DEFAULT '',school_email TEXT NOT NULL DEFAULT '',logo_url TEXT NOT NULL DEFAULT '',updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS counters(institution_id TEXT NOT NULL,kind TEXT NOT NULL,year TEXT NOT NULL,value INTEGER NOT NULL DEFAULT 0,PRIMARY KEY(institution_id,kind,year));
CREATE TABLE IF NOT EXISTS audit_logs(id TEXT PRIMARY KEY,institution_id TEXT NOT NULL REFERENCES institutions(id),user_id TEXT,action TEXT NOT NULL,entity TEXT NOT NULL,entity_id TEXT,details TEXT NOT NULL DEFAULT '{}',created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS subscription_payments(id TEXT PRIMARY KEY,institution_id TEXT NOT NULL REFERENCES institutions(id),plan TEXT NOT NULL,student_capacity INTEGER NOT NULL,amount REAL NOT NULL,razorpay_payment_id TEXT NOT NULL UNIQUE,payment_date TEXT NOT NULL,starts_at TEXT NOT NULL,ends_at TEXT NOT NULL,status TEXT NOT NULL,created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS subscription_plans(id TEXT PRIMARY KEY,name TEXT NOT NULL UNIQUE,student_limit INTEGER NOT NULL,price REAL NOT NULL,billing_period TEXT NOT NULL DEFAULT 'year',active INTEGER NOT NULL DEFAULT 1,created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS subscriptions(id TEXT PRIMARY KEY,institution_id TEXT NOT NULL REFERENCES institutions(id),plan_id TEXT NOT NULL REFERENCES subscription_plans(id),student_capacity INTEGER NOT NULL,amount_paid REAL NOT NULL DEFAULT 0,status TEXT NOT NULL,activation_date TEXT,expiry_date TEXT,razorpay_order_id TEXT NOT NULL UNIQUE,razorpay_payment_id TEXT UNIQUE,razorpay_signature TEXT,created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS razorpay_webhook_events(id TEXT PRIMARY KEY,event_type TEXT NOT NULL,created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE INDEX IF NOT EXISTS idx_students_institution ON students(institution_id);CREATE INDEX IF NOT EXISTS idx_students_search ON students(institution_id,name,admission);CREATE INDEX IF NOT EXISTS idx_sessions_user ON sessions(user_id);CREATE INDEX IF NOT EXISTS idx_module_records ON module_records(institution_id,module);CREATE INDEX IF NOT EXISTS idx_teachers_institution ON teachers(institution_id,name);CREATE INDEX IF NOT EXISTS idx_attendance_scope ON attendance(institution_id,date,status);CREATE INDEX IF NOT EXISTS idx_attendance_student ON attendance(student_id,date);CREATE INDEX IF NOT EXISTS idx_fees_scope ON fees(institution_id,status,due_date);CREATE INDEX IF NOT EXISTS idx_payments_scope ON payments(institution_id,payment_date,created_at);CREATE INDEX IF NOT EXISTS idx_payments_student ON payments(student_id,payment_date);CREATE INDEX IF NOT EXISTS idx_activity_scope ON activities(institution_id,timestamp);CREATE INDEX IF NOT EXISTS idx_audit_scope ON audit_logs(institution_id,created_at);
`);
const seedPlan=db.prepare("INSERT INTO subscription_plans(id,name,student_limit,price,billing_period,active)VALUES(?,?,?,?,?,?) ON CONFLICT(id) DO UPDATE SET name=excluded.name,student_limit=excluded.student_limit,price=excluded.price,billing_period=excluded.billing_period,active=excluded.active,updated_at=CURRENT_TIMESTAMP");for(const plan of SUBSCRIPTION_PLANS)seedPlan.run(plan.id,plan.name,plan.studentLimit,plan.price,plan.billingPeriod,plan.active?1:0);
function columns(table:string){return new Set((db.prepare(`PRAGMA table_info(${table})`).all() as unknown as {name:string}[]).map(x=>x.name));}
function addColumn(table:string,name:string,definition:string){if(!columns(table).has(name))db.exec(`ALTER TABLE ${table} ADD COLUMN ${name} ${definition}`);}
[["gender","TEXT NOT NULL DEFAULT ''"],["date_of_birth","TEXT NOT NULL DEFAULT ''"],["class_name","TEXT NOT NULL DEFAULT ''"],["section","TEXT NOT NULL DEFAULT ''"],["roll_number","TEXT NOT NULL DEFAULT ''"],["parent_phone","TEXT NOT NULL DEFAULT ''"],["parent_email","TEXT NOT NULL DEFAULT ''"],["address","TEXT NOT NULL DEFAULT ''"],["admission_date","TEXT NOT NULL DEFAULT ''"],["total_fee","REAL NOT NULL DEFAULT 0"],["paid_fee","REAL NOT NULL DEFAULT 0"],["pending_fee","REAL NOT NULL DEFAULT 0"],["status","TEXT NOT NULL DEFAULT 'Active'"],["updated_at","TEXT NOT NULL DEFAULT ''"]].forEach(([name,definition])=>addColumn("students",name,definition));
db.exec(`UPDATE students SET class_name=CASE WHEN instr(grade,'-')>0 THEN trim(substr(grade,1,instr(grade,'-')-1)) ELSE grade END WHERE class_name='';UPDATE students SET section=CASE WHEN instr(grade,'-')>0 THEN trim(substr(grade,instr(grade,'-')+1)) ELSE '' END WHERE section='';UPDATE students SET pending_fee=MAX(total_fee-paid_fee,0) WHERE pending_fee=0 AND total_fee>0;`);

function audit(institutionId:string,userId:string|undefined,action:string,entity:string,entityId:string|undefined,details:Record<string,unknown>={}){db.prepare("INSERT INTO audit_logs(id,institution_id,user_id,action,entity,entity_id,details)VALUES(?,?,?,?,?,?,?)").run(randomUUID(),institutionId,userId??null,action,entity,entityId??null,JSON.stringify(details));}
function activity(institutionId:string,type:string,title:string,description:string,studentId?:string,paymentId?:string,amount?:number){db.prepare("INSERT INTO activities(id,institution_id,type,title,description,student_id,payment_id,amount)VALUES(?,?,?,?,?,?,?,?)").run(randomUUID(),institutionId,type,title,description,studentId??null,paymentId??null,amount??null);}
function notify(institutionId:string,userId:string|undefined,type:string,title:string,description:string){db.prepare("INSERT INTO notifications(id,institution_id,user_id,type,title,description)VALUES(?,?,?,?,?,?)").run(randomUUID(),institutionId,userId??null,type,title,description);}
function nextNumber(institutionId:string,kind:"REC"|"INV",date=new Date()){const year=String(date.getFullYear());db.prepare("INSERT INTO counters(institution_id,kind,year,value)VALUES(?,?,?,1) ON CONFLICT(institution_id,kind,year) DO UPDATE SET value=value+1").run(institutionId,kind,year);const row=db.prepare("SELECT value FROM counters WHERE institution_id=? AND kind=? AND year=?").get(institutionId,kind,year) as {value:number};return `${kind}-${year}-${String(row.value).padStart(6,"0")}`;}
export function getInstitution(institutionId:string){return db.prepare("SELECT i.id,i.name,COALESCE(s.school_address,'') AS address,COALESCE(s.school_phone,'') AS phone,COALESCE(s.school_email,'') AS email,COALESCE(s.logo_url,'') AS logoUrl,COALESCE(s.academic_year,'2026-2027') AS academicYear FROM institutions i LEFT JOIN settings s ON s.institution_id=i.id WHERE i.id=?").get(institutionId) as {id:string;name:string;address:string;phone:string;email:string;logoUrl:string;academicYear:string};}
export function findUserByEmail(email:string){return db.prepare("SELECT id,email,name,password_hash AS passwordHash,role,institution_id AS institutionId FROM users WHERE email=?").get(email.toLowerCase())as(DbUser&{passwordHash:string})|undefined;}
export function createAccount(input:{name:string;email:string;institution:string;passwordHash:string}){const institutionId=randomUUID(),userId=randomUUID();db.exec("BEGIN IMMEDIATE");try{db.prepare("INSERT INTO institutions(id,name)VALUES(?,?)").run(institutionId,input.institution);db.prepare("INSERT INTO users(id,email,name,password_hash,role,institution_id)VALUES(?,?,?,?,?,?)").run(userId,input.email.toLowerCase(),input.name,input.passwordHash,"SCHOOL_ADMIN",institutionId);db.prepare("INSERT INTO settings(institution_id,school_email)VALUES(?,?)").run(institutionId,input.email.toLowerCase());db.exec("COMMIT");return{id:userId,email:input.email.toLowerCase(),name:input.name,role:"SCHOOL_ADMIN",institutionId}as DbUser}catch(e){db.exec("ROLLBACK");throw e;}}
export function createSession(userId:string){const token=randomUUID()+randomUUID().replaceAll("-","");const expires=new Date(Date.now()+7*864e5);db.prepare("DELETE FROM sessions WHERE expires_at < ?").run(new Date().toISOString());db.prepare("INSERT INTO sessions(token,user_id,expires_at)VALUES(?,?,?)").run(token,userId,expires.toISOString());return{token,expires};}
export function getUserBySession(token:string){return db.prepare("SELECT u.id,u.email,u.name,u.role,u.institution_id AS institutionId FROM sessions s JOIN users u ON u.id=s.user_id WHERE s.token=? AND s.expires_at>?").get(token,new Date().toISOString())as DbUser|undefined;}
export function deleteSession(token:string){db.prepare("DELETE FROM sessions WHERE token=?").run(token);}

const studentSelect=`SELECT s.id,s.name,s.admission,s.gender,s.date_of_birth AS dateOfBirth,s.class_name AS className,s.section,s.grade,s.roll_number AS rollNumber,s.parent,s.parent_phone AS parentPhone,s.parent_email AS parentEmail,s.address,s.admission_date AS admissionDate,s.attendance,s.fee,s.total_fee AS totalFee,s.paid_fee AS paidFee,s.pending_fee AS pendingFee,s.status,s.created_at AS createdAt FROM students s`;
function refreshFeeStatuses(institutionId:string){const today=new Date().toISOString().slice(0,10);db.prepare("UPDATE fees SET status=CASE WHEN pending_amount=0 THEN 'Paid' WHEN due_date<? THEN 'Overdue' WHEN paid_amount>0 THEN 'Partially Paid' ELSE 'Pending' END WHERE institution_id=?").run(today,institutionId);db.prepare("UPDATE students SET fee=CASE WHEN EXISTS(SELECT 1 FROM fees WHERE student_id=students.id AND status='Overdue') THEN 'Overdue' WHEN pending_fee=0 THEN 'Paid' WHEN paid_fee>0 THEN 'Partially Paid' ELSE 'Pending' END WHERE institution_id=?").run(institutionId);}
export function listStudents(institutionId:string,filters:{search?:string;className?:string;section?:string;fee?:string;limit?:number;offset?:number}={}){refreshFeeStatuses(institutionId);const where=["s.institution_id=?"],params:(string|number)[]=[institutionId];if(filters.search){where.push("(s.name LIKE ? OR s.admission LIKE ? OR s.parent_phone LIKE ?)");const q=`%${filters.search}%`;params.push(q,q,q);}if(filters.className){where.push("s.class_name=?");params.push(filters.className);}if(filters.section){where.push("s.section=?");params.push(filters.section);}if(filters.fee){where.push("s.fee=?");params.push(filters.fee);}let sql=`${studentSelect} WHERE ${where.join(" AND ")} ORDER BY s.created_at DESC`;if(filters.limit){sql+=" LIMIT ? OFFSET ?";params.push(filters.limit,filters.offset??0);}return db.prepare(sql).all(...params) as unknown as DbStudent[];}
export function getStudent(institutionId:string,id:string){return db.prepare(`${studentSelect} WHERE s.institution_id=? AND s.id=?`).get(institutionId,id) as DbStudent|undefined;}
export type StudentInput={name:string;admission:string;gender:string;dateOfBirth:string;className:string;section:string;rollNumber:string;parent:string;parentPhone:string;parentEmail:string;address:string;admissionDate:string;totalFee:number;academicYear:string;dueDate:string};
export function addStudent(institutionId:string,input:StudentInput,userId?:string){const studentId=randomUUID(),today=new Date();db.exec("BEGIN IMMEDIATE");try{const admission=input.admission||`EDL-${today.getFullYear()}-${randomUUID().slice(0,6).toUpperCase()}`;const pending=Math.max(input.totalFee,0);db.prepare("INSERT INTO students(id,institution_id,name,admission,gender,date_of_birth,class_name,section,grade,roll_number,parent,parent_phone,parent_email,address,admission_date,total_fee,paid_fee,pending_fee,attendance,fee,status,updated_at)VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,CURRENT_TIMESTAMP)").run(studentId,institutionId,input.name,admission,input.gender,input.dateOfBirth,input.className,input.section,`${input.className}${input.section?`-${input.section}`:""}`,input.rollNumber,input.parent,input.parentPhone,input.parentEmail,input.address,input.admissionDate,input.totalFee,0,pending,100,pending>0?"Pending":"Paid","Active");if(input.totalFee>0){const invoice=nextNumber(institutionId,"INV",today);db.prepare("INSERT INTO fees(id,institution_id,student_id,invoice_number,academic_year,total_amount,final_amount,pending_amount,due_date,status)VALUES(?,?,?,?,?,?,?,?,?,?)").run(randomUUID(),institutionId,studentId,invoice,input.academicYear,input.totalFee,input.totalFee,input.totalFee,input.dueDate,"Pending");}audit(institutionId,userId,"Student Added","Student",studentId,{name:input.name,admission});activity(institutionId,"student","New student added",`${input.name} (${admission}) was enrolled`,studentId);notify(institutionId,userId,"student","New student added",`${input.name} was enrolled successfully.`);db.exec("COMMIT");return getStudent(institutionId,studentId)!;}catch(e){db.exec("ROLLBACK");throw e;}}
export function updateStudent(institutionId:string,id:string,input:Partial<StudentInput>,userId?:string){const existing=getStudent(institutionId,id);if(!existing)throw new Error("Student not found");const merged={...existing,...input};db.prepare("UPDATE students SET name=?,admission=?,gender=?,date_of_birth=?,class_name=?,section=?,grade=?,roll_number=?,parent=?,parent_phone=?,parent_email=?,address=?,admission_date=?,updated_at=CURRENT_TIMESTAMP WHERE id=? AND institution_id=?").run(merged.name,merged.admission,merged.gender,merged.dateOfBirth,merged.className,merged.section,`${merged.className}${merged.section?`-${merged.section}`:""}`,merged.rollNumber,merged.parent,merged.parentPhone,merged.parentEmail,merged.address,merged.admissionDate,id,institutionId);audit(institutionId,userId,"Student Updated","Student",id,{name:merged.name});return getStudent(institutionId,id)!;}
export function deleteStudent(institutionId:string,id:string,userId?:string){const student=getStudent(institutionId,id);if(!student)return false;const paymentCount=(db.prepare("SELECT COUNT(*) count FROM payments WHERE student_id=?").get(id) as {count:number}).count;if(paymentCount>0)throw new Error("Students with payment history cannot be deleted. Set them inactive instead.");db.prepare("DELETE FROM students WHERE id=? AND institution_id=?").run(id,institutionId);audit(institutionId,userId,"Student Deleted","Student",id,{name:student.name});return true;}

export function listTeachers(institutionId:string,search=""){const q=`%${search}%`;return db.prepare("SELECT id,name,employee_id AS employeeId,email,phone,department,subject,assigned_classes AS classes,joining_date AS joiningDate,salary,status,created_at AS createdAt FROM teachers WHERE institution_id=? AND (name LIKE ? OR employee_id LIKE ? OR subject LIKE ?) ORDER BY created_at DESC").all(institutionId,q,q,q) as unknown as DbTeacher[];}
export function saveTeacher(institutionId:string,input:Omit<DbTeacher,"id"|"createdAt">,userId?:string){const id=randomUUID();db.prepare("INSERT INTO teachers(id,institution_id,name,employee_id,email,phone,department,subject,assigned_classes,joining_date,salary,status)VALUES(?,?,?,?,?,?,?,?,?,?,?,?)").run(id,institutionId,input.name,input.employeeId,input.email,input.phone,input.department,input.subject,input.classes,input.joiningDate,input.salary,input.status);audit(institutionId,userId,"Teacher Added","Teacher",id,{name:input.name});activity(institutionId,"teacher","New teacher added",`${input.name} joined ${input.department}`);return listTeachers(institutionId).find(x=>x.id===id)!;}
export function updateTeacher(institutionId:string,id:string,input:Omit<DbTeacher,"id"|"createdAt">,userId?:string){db.prepare("UPDATE teachers SET name=?,employee_id=?,email=?,phone=?,department=?,subject=?,assigned_classes=?,joining_date=?,salary=?,status=?,updated_at=CURRENT_TIMESTAMP WHERE id=? AND institution_id=?").run(input.name,input.employeeId,input.email,input.phone,input.department,input.subject,input.classes,input.joiningDate,input.salary,input.status,id,institutionId);audit(institutionId,userId,"Teacher Updated","Teacher",id,{name:input.name});return listTeachers(institutionId).find(x=>x.id===id);}
export function deleteTeacher(institutionId:string,id:string,userId?:string){const result=db.prepare("DELETE FROM teachers WHERE id=? AND institution_id=?").run(id,institutionId);if(result.changes)audit(institutionId,userId,"Teacher Deleted","Teacher",id);return result.changes>0;}
export function listClasses(institutionId:string,academicYear?:string){const year=academicYear??getInstitution(institutionId).academicYear;return db.prepare("SELECT c.id,c.name,c.section,c.teacher,c.academic_year AS academicYear,c.capacity,c.status,COUNT(s.id) AS currentStudents FROM classes c LEFT JOIN students s ON s.institution_id=c.institution_id AND s.class_name=c.name AND s.section=c.section WHERE c.institution_id=? AND c.academic_year=? GROUP BY c.id ORDER BY c.name,c.section").all(institutionId,year) as unknown as DbClass[];}
export function saveClass(institutionId:string,input:Omit<DbClass,"id"|"currentStudents">,userId?:string){const id=randomUUID();db.prepare("INSERT INTO classes(id,institution_id,name,section,teacher,academic_year,capacity,status)VALUES(?,?,?,?,?,?,?,?)").run(id,institutionId,input.name,input.section,input.teacher,input.academicYear,input.capacity,input.status);audit(institutionId,userId,"Class Added","Class",id,input);return listClasses(institutionId,input.academicYear).find(x=>x.id===id)!;}

export function attendanceRoster(institutionId:string,date:string,className:string,section:string){return db.prepare("SELECT s.id AS studentId,s.name,s.admission,s.class_name AS className,s.section,COALESCE(a.status,'Present') AS status,COALESCE(a.remarks,'') AS remarks FROM students s LEFT JOIN attendance a ON a.student_id=s.id AND a.date=? WHERE s.institution_id=? AND s.class_name=? AND s.section=? AND s.status='Active' ORDER BY s.name").all(date,institutionId,className,section) as unknown as {studentId:string;name:string;admission:string;className:string;section:string;status:string;remarks:string}[];}
export function listAttendance(institutionId:string,filters:{date?:string;className?:string;section?:string;status?:string}={}){const where=["a.institution_id=?"],params:string[]=[institutionId];for(const[k,column]of [["date","a.date"],["className","s.class_name"],["section","s.section"],["status","a.status"]]as const){if(filters[k]){where.push(`${column}=?`);params.push(filters[k]!);}}return db.prepare(`SELECT a.id,a.date,s.name AS studentName,s.admission,s.class_name AS className,s.section,a.status,a.remarks,a.marked_by AS markedBy FROM attendance a JOIN students s ON s.id=a.student_id WHERE ${where.join(" AND ")} ORDER BY a.date DESC,s.name`).all(...params);}
export function findStudentByAdmission(institutionId:string,admission:string){return db.prepare(`${studentSelect} WHERE s.institution_id=? AND s.admission=?`).get(institutionId,admission) as DbStudent|undefined;}
export function markAttendance(institutionId:string,date:string,records:{studentId:string;status:string;remarks?:string}[],markedBy:string,userId?:string){db.exec("BEGIN IMMEDIATE");try{const allowed=new Set((db.prepare("SELECT id FROM students WHERE institution_id=?").all(institutionId) as unknown as {id:string}[]).map(x=>x.id));const stmt=db.prepare("INSERT INTO attendance(id,institution_id,student_id,date,status,remarks,marked_by)VALUES(?,?,?,?,?,?,?) ON CONFLICT(student_id,date) DO UPDATE SET status=excluded.status,remarks=excluded.remarks,marked_by=excluded.marked_by,updated_at=CURRENT_TIMESTAMP");for(const item of records){if(!allowed.has(item.studentId))throw new Error("Invalid student");stmt.run(randomUUID(),institutionId,item.studentId,date,item.status,item.remarks??"",markedBy);}db.prepare("UPDATE students SET attendance=COALESCE((SELECT ROUND(100.0*SUM(CASE WHEN status IN ('Present','Late') THEN 1 ELSE 0 END)/COUNT(*)) FROM attendance WHERE student_id=students.id),100),updated_at=CURRENT_TIMESTAMP WHERE institution_id=?").run(institutionId);audit(institutionId,userId,"Attendance Updated","Attendance",date,{count:records.length});activity(institutionId,"attendance","Attendance updated",`${records.length} records marked for ${date}`);db.exec("COMMIT");}catch(e){db.exec("ROLLBACK");throw e;}}

export function listFees(institutionId:string,filters:{search?:string;className?:string;section?:string;status?:string}={}){refreshFeeStatuses(institutionId);const where=["f.institution_id=?"],params:string[]=[institutionId];if(filters.search){where.push("(s.name LIKE ? OR s.admission LIKE ? OR f.invoice_number LIKE ?)");const q=`%${filters.search}%`;params.push(q,q,q);}if(filters.className){where.push("s.class_name=?");params.push(filters.className);}if(filters.section){where.push("s.section=?");params.push(filters.section);}if(filters.status){where.push("f.status=?");params.push(filters.status);}return db.prepare(`SELECT f.id,f.student_id AS studentId,s.name AS studentName,s.admission,s.class_name AS className,s.section,f.invoice_number AS invoiceNumber,f.fee_type AS feeType,f.academic_year AS academicYear,f.total_amount AS totalAmount,f.discount,f.final_amount AS finalAmount,f.paid_amount AS paidAmount,f.pending_amount AS pendingAmount,f.due_date AS dueDate,f.status FROM fees f JOIN students s ON s.id=f.student_id WHERE ${where.join(" AND ")} ORDER BY f.due_date,f.created_at DESC`).all(...params) as unknown as Record<string,string|number>[];}
export function getFee(institutionId:string,id:string){return db.prepare("SELECT f.id,f.student_id AS studentId,s.name AS studentName,s.admission,s.class_name AS className,s.section,s.parent,f.invoice_number AS invoiceNumber,f.fee_type AS feeType,f.academic_year AS academicYear,f.total_amount AS totalAmount,f.paid_amount AS paidAmount,f.pending_amount AS pendingAmount,f.due_date AS dueDate,f.status FROM fees f JOIN students s ON s.id=f.student_id WHERE f.institution_id=? AND f.id=?").get(institutionId,id) as Record<string,string|number>|undefined;}
export function createFee(institutionId:string,studentId:string,input:{feeType:string;academicYear:string;totalAmount:number;dueDate:string},userId?:string){const student=getStudent(institutionId,studentId);if(!student)throw new Error("Student not found");const id=randomUUID();db.exec("BEGIN IMMEDIATE");try{const invoice=nextNumber(institutionId,"INV");db.prepare("INSERT INTO fees(id,institution_id,student_id,invoice_number,fee_type,academic_year,total_amount,final_amount,pending_amount,due_date,status)VALUES(?,?,?,?,?,?,?,?,?,?,?)").run(id,institutionId,studentId,invoice,input.feeType,input.academicYear,input.totalAmount,input.totalAmount,input.totalAmount,input.dueDate,"Pending");db.prepare("UPDATE students SET total_fee=total_fee+?,pending_fee=pending_fee+?,fee='Pending',updated_at=CURRENT_TIMESTAMP WHERE id=?").run(input.totalAmount,input.totalAmount,studentId);audit(institutionId,userId,"Fee Created","Fee",id,{invoice,totalAmount:input.totalAmount});db.exec("COMMIT");return id;}catch(e){db.exec("ROLLBACK");throw e;}}
export function recordPayment(institutionId:string,userId:string,input:{feeId:string;amount:number;method:string;paymentDate:string;transactionId:string;notes:string}){db.exec("BEGIN IMMEDIATE");try{const fee=getFee(institutionId,input.feeId);if(!fee)throw new Error("Fee invoice not found");const pending=Number(fee.pendingAmount);if(input.amount<=0)throw new Error("Payment amount must be greater than zero");if(input.amount>pending)throw new Error("Payment cannot exceed the remaining amount");const receiptNumber=nextNumber(institutionId,"REC",new Date(input.paymentDate));const id=randomUUID(),previouslyPaid=Number(fee.paidAmount),totalPaid=previouslyPaid+input.amount,remaining=Math.max(Number(fee.totalAmount)-totalPaid,0),status=remaining===0?"Paid":"Partially Paid";db.prepare("INSERT INTO payments(id,institution_id,student_id,fee_id,receipt_number,amount,payment_method,transaction_id,payment_date,status,notes,created_by)VALUES(?,?,?,?,?,?,?,?,?,?,?,?)").run(id,institutionId,String(fee.studentId),input.feeId,receiptNumber,input.amount,input.method,input.transactionId,input.paymentDate,"Success",input.notes,userId);db.prepare("UPDATE fees SET paid_amount=?,pending_amount=?,status=?,updated_at=CURRENT_TIMESTAMP WHERE id=?").run(totalPaid,remaining,status,input.feeId);db.prepare("UPDATE students SET paid_fee=(SELECT COALESCE(SUM(paid_amount),0) FROM fees WHERE student_id=?),pending_fee=(SELECT COALESCE(SUM(pending_amount),0) FROM fees WHERE student_id=?),total_fee=(SELECT COALESCE(SUM(final_amount),0) FROM fees WHERE student_id=?),fee=?,updated_at=CURRENT_TIMESTAMP WHERE id=?").run(fee.studentId,fee.studentId,fee.studentId,status,fee.studentId);db.prepare("INSERT INTO receipts(id,institution_id,receipt_number,student_id,payment_id,invoice_number,amount,payment_method,transaction_id,issued_date)VALUES(?,?,?,?,?,?,?,?,?,?)").run(randomUUID(),institutionId,receiptNumber,fee.studentId,id,fee.invoiceNumber,input.amount,input.method,input.transactionId,input.paymentDate);activity(institutionId,"payment","Fee payment received",`${fee.studentName} paid ₹${input.amount.toLocaleString("en-IN")}`,String(fee.studentId),id,input.amount);audit(institutionId,userId,"Payment Created","Payment",id,{amount:input.amount,receiptNumber});audit(institutionId,userId,"Receipt Generated","Receipt",receiptNumber,{paymentId:id});notify(institutionId,userId,"payment","New payment received",`${fee.studentName} paid ₹${input.amount.toLocaleString("en-IN")}.`);db.exec("COMMIT");return getPayment(institutionId,id)!;}catch(e){db.exec("ROLLBACK");throw e;}}
const paymentSelect=`SELECT p.id,p.fee_id AS feeId,p.student_id AS studentId,s.name AS studentName,s.admission,s.class_name AS className,s.section,f.invoice_number AS invoiceNumber,p.receipt_number AS receiptNumber,p.amount,p.payment_method AS method,p.transaction_id AS transactionId,p.payment_date AS paymentDate,p.status,p.notes,(SELECT COALESCE(SUM(p2.amount),0) FROM payments p2 WHERE p2.fee_id=p.fee_id AND p2.rowid<p.rowid) AS previouslyPaid,(SELECT COALESCE(SUM(p2.amount),0) FROM payments p2 WHERE p2.fee_id=p.fee_id AND p2.rowid<=p.rowid) AS totalPaid,(f.final_amount-(SELECT COALESCE(SUM(p2.amount),0) FROM payments p2 WHERE p2.fee_id=p.fee_id AND p2.rowid<=p.rowid)) AS remainingBalance,p.created_at AS createdAt FROM payments p JOIN students s ON s.id=p.student_id JOIN fees f ON f.id=p.fee_id`;
export function getPayment(institutionId:string,id:string){return db.prepare(`${paymentSelect} WHERE p.institution_id=? AND p.id=?`).get(institutionId,id) as DbPayment|undefined;}
export function listPayments(institutionId:string,filters:{search?:string;className?:string;section?:string;method?:string;status?:string;from?:string;to?:string;studentId?:string;limit?:number;offset?:number}={}){const where=["p.institution_id=?"],params:(string|number)[]=[institutionId];if(filters.search){where.push("(s.name LIKE ? OR s.admission LIKE ? OR p.receipt_number LIKE ? OR f.invoice_number LIKE ? OR p.transaction_id LIKE ? OR s.parent_phone LIKE ?)");const q=`%${filters.search}%`;params.push(q,q,q,q,q,q);}for(const[k,column]of [["className","s.class_name"],["section","s.section"],["method","p.payment_method"],["status","p.status"],["studentId","p.student_id"]]as const){if(filters[k]){where.push(`${column}=?`);params.push(filters[k]!);}}if(filters.from){where.push("p.payment_date>=?");params.push(filters.from);}if(filters.to){where.push("p.payment_date<=?");params.push(filters.to);}let sql=`${paymentSelect} WHERE ${where.join(" AND ")} ORDER BY p.payment_date DESC,p.created_at DESC`;if(filters.limit){sql+=" LIMIT ? OFFSET ?";params.push(filters.limit,filters.offset??0);}return db.prepare(sql).all(...params) as unknown as DbPayment[];}
export function getReceipt(institutionId:string,receiptNumber:string){return db.prepare(`${paymentSelect} WHERE p.institution_id=? AND p.receipt_number=?`).get(institutionId,receiptNumber) as DbPayment|undefined;}

export function dashboardData(institutionId:string){refreshFeeStatuses(institutionId);const students=(db.prepare("SELECT COUNT(*) count FROM students WHERE institution_id=? AND status='Active'").get(institutionId)as{count:number}).count,teachers=(db.prepare("SELECT COUNT(*) count FROM teachers WHERE institution_id=? AND status='Active'").get(institutionId)as{count:number}).count,today=new Date().toISOString().slice(0,10),month=today.slice(0,7);const attendance=db.prepare("SELECT SUM(status IN ('Present','Late')) present,SUM(status='Absent') absent FROM attendance WHERE institution_id=? AND date=?").get(institutionId,today)as{present:number|null;absent:number|null};const fees=db.prepare("SELECT COALESCE(SUM(final_amount),0) total,COALESCE(SUM(paid_amount),0) collected,COALESCE(SUM(pending_amount),0) pending,COALESCE(SUM(CASE WHEN due_date<? AND pending_amount>0 THEN pending_amount ELSE 0 END),0) overdue FROM fees WHERE institution_id=?").get(today,institutionId)as{total:number;collected:number;pending:number;overdue:number};const collections=db.prepare("SELECT COALESCE(SUM(CASE WHEN payment_date=? THEN amount ELSE 0 END),0) today,COALESCE(SUM(CASE WHEN substr(payment_date,1,7)=? THEN amount ELSE 0 END),0) month,COUNT(*) transactions FROM payments WHERE institution_id=? AND status='Success'").get(today,month,institutionId)as{today:number;month:number;transactions:number};const monthly=db.prepare("SELECT substr(payment_date,1,7) month,SUM(amount) amount FROM payments WHERE institution_id=? AND status='Success' GROUP BY substr(payment_date,1,7) ORDER BY month DESC LIMIT 12").all(institutionId)as unknown as{month:string;amount:number}[];const methods=db.prepare("SELECT payment_method method,SUM(amount) amount FROM payments WHERE institution_id=? AND status='Success' GROUP BY payment_method ORDER BY amount DESC").all(institutionId);return{students,teachers,present:attendance.present??0,absent:attendance.absent??0,fees,collections,monthly:monthly.reverse(),methods,recentPayments:listPayments(institutionId,{limit:5}),activities:listActivities(institutionId,6)};}
export function listActivities(institutionId:string,limit=25){return db.prepare("SELECT id,type,title,description,student_id AS studentId,payment_id AS paymentId,amount,timestamp,status FROM activities WHERE institution_id=? ORDER BY timestamp DESC LIMIT ?").all(institutionId,limit);}
export function listNotifications(institutionId:string,userId:string){return db.prepare("SELECT id,type,title,description,read_at AS readAt,created_at AS createdAt FROM notifications WHERE institution_id=? AND (user_id IS NULL OR user_id=?) ORDER BY created_at DESC LIMIT 25").all(institutionId,userId);}
export function markNotificationsRead(institutionId:string,userId:string){db.prepare("UPDATE notifications SET read_at=CURRENT_TIMESTAMP WHERE institution_id=? AND (user_id IS NULL OR user_id=?) AND read_at IS NULL").run(institutionId,userId);}
export function updateSettings(institutionId:string,input:{academicYear:string;address:string;phone:string;email:string},userId:string){db.prepare("INSERT INTO settings(institution_id,academic_year,school_address,school_phone,school_email)VALUES(?,?,?,?,?) ON CONFLICT(institution_id) DO UPDATE SET academic_year=excluded.academic_year,school_address=excluded.school_address,school_phone=excluded.school_phone,school_email=excluded.school_email,updated_at=CURRENT_TIMESTAMP").run(institutionId,input.academicYear,input.address,input.phone,input.email);audit(institutionId,userId,"Settings Updated","Settings",institutionId,input);return getInstitution(institutionId);}
export function listAuditLogs(institutionId:string,limit=100){return db.prepare("SELECT a.id,a.action,a.entity,a.entity_id AS entityId,a.details,a.created_at AS createdAt,u.name AS userName FROM audit_logs a LEFT JOIN users u ON u.id=a.user_id WHERE a.institution_id=? ORDER BY a.created_at DESC LIMIT ?").all(institutionId,limit);}
export function logExport(institutionId:string,userId:string,entity:string,count:number){audit(institutionId,userId,"Excel Exported",entity,undefined,{count});}
export function logImport(institutionId:string,userId:string,entity:string,count:number){audit(institutionId,userId,"Excel Imported",entity,undefined,{count});activity(institutionId,"import","Import completed",`${count} ${entity.toLowerCase()} records imported`);notify(institutionId,userId,"import","Import completed",`${count} ${entity.toLowerCase()} records imported successfully.`);}
export function listSubscriptionPayments(institutionId:string){return db.prepare("SELECT id,plan,student_capacity AS studentCapacity,amount,razorpay_payment_id AS razorpayPaymentId,payment_date AS paymentDate,starts_at AS startsAt,ends_at AS endsAt,status FROM subscription_payments WHERE institution_id=? ORDER BY payment_date DESC").all(institutionId);}
export type SubscriptionSummary={status:SubscriptionStatus;planId:string|null;planName:string|null;studentCapacity:number|null;amountPaid:number;activationDate:string|null;expiryDate:string|null;razorpayOrderId:string|null;razorpayPaymentId:string|null;razorpaySignature:string|null;studentUsage:number};
export function getSubscription(institutionId:string):SubscriptionSummary{const row=db.prepare("SELECT s.status,s.plan_id AS planId,p.name AS planName,s.student_capacity AS studentCapacity,s.amount_paid AS amountPaid,s.activation_date AS activationDate,s.expiry_date AS expiryDate,s.razorpay_order_id AS razorpayOrderId,s.razorpay_payment_id AS razorpayPaymentId,s.razorpay_signature AS razorpaySignature FROM subscriptions s JOIN subscription_plans p ON p.id=s.plan_id WHERE s.institution_id=? ORDER BY CASE WHEN s.status='ACTIVE' AND s.expiry_date>datetime('now') THEN 0 ELSE 1 END,s.created_at DESC LIMIT 1").get(institutionId)as Omit<SubscriptionSummary,"studentUsage">|undefined;const usage=(db.prepare("SELECT COUNT(*) count FROM students WHERE institution_id=? AND status='Active'").get(institutionId)as{count:number}).count;if(!row)return{status:"UNPAID",planId:null,planName:null,studentCapacity:null,amountPaid:0,activationDate:null,expiryDate:null,razorpayOrderId:null,razorpayPaymentId:null,razorpaySignature:null,studentUsage:usage};const status=effectiveStatus(row.status,row.expiryDate??undefined);if(status!==row.status)db.prepare("UPDATE subscriptions SET status=?,updated_at=CURRENT_TIMESTAMP WHERE razorpay_order_id=?").run(status,row.razorpayOrderId);return{...row,status,studentUsage:usage};}
export function hasActiveSubscription(institutionId:string){return getSubscription(institutionId).status==="ACTIVE";}
export function assertStudentCapacity(institutionId:string,additional=1){const subscription=getSubscription(institutionId);if(subscription.status!=="ACTIVE"||!subscription.studentCapacity)throw new Error("SUBSCRIPTION_REQUIRED");if(subscription.studentUsage+additional>subscription.studentCapacity)throw new Error(`CAPACITY_EXCEEDED:${subscription.studentUsage}:${subscription.studentCapacity}:${additional}`);return subscription;}
export function createPendingSubscription(institutionId:string,planId:string,orderId:string){const plan=getPlan(planId);if(!plan)throw new Error("Invalid subscription plan");const id=randomUUID();db.prepare("INSERT INTO subscriptions(id,institution_id,plan_id,student_capacity,amount_paid,status,razorpay_order_id)VALUES(?,?,?,?,?,'PENDING',?)").run(id,institutionId,plan.id,plan.studentLimit,plan.price,orderId);return getSubscription(institutionId);}
export function failSubscription(orderId:string,status:"FAILED"|"CANCELLED"="FAILED"){db.prepare("UPDATE subscriptions SET status=?,updated_at=CURRENT_TIMESTAMP WHERE razorpay_order_id=? AND status!='ACTIVE'").run(status,orderId);}
export function activateSubscription(orderId:string,paymentId:string,signature:string){db.exec("BEGIN IMMEDIATE");try{const row=db.prepare("SELECT id,institution_id AS institutionId,plan_id AS planId,student_capacity AS studentCapacity,amount_paid AS amountPaid,status,expiry_date AS expiryDate FROM subscriptions WHERE razorpay_order_id=?").get(orderId)as{id:string;institutionId:string;planId:string;studentCapacity:number;amountPaid:number;status:string;expiryDate:string|null}|undefined;if(!row)throw new Error("Subscription order not found");if(row.status==="ACTIVE"&&db.prepare("SELECT razorpay_payment_id paymentId FROM subscriptions WHERE id=?").get(row.id)!==undefined){db.exec("COMMIT");return getSubscription(row.institutionId);}const now=new Date(),current=getSubscription(row.institutionId),base=current.status==="ACTIVE"&&current.expiryDate&&new Date(current.expiryDate)>now?new Date(current.expiryDate):now,expiry=addOneYear(base);db.prepare("UPDATE subscriptions SET status='ACTIVE',activation_date=?,expiry_date=?,razorpay_payment_id=?,razorpay_signature=?,updated_at=CURRENT_TIMESTAMP WHERE id=?").run(now.toISOString(),expiry.toISOString(),paymentId,signature,row.id);db.prepare("INSERT OR IGNORE INTO subscription_payments(id,institution_id,plan,student_capacity,amount,razorpay_payment_id,payment_date,starts_at,ends_at,status)SELECT ?,s.institution_id,p.name,s.student_capacity,s.amount_paid,?,?,?,?,'ACTIVE' FROM subscriptions s JOIN subscription_plans p ON p.id=s.plan_id WHERE s.id=?").run(randomUUID(),paymentId,now.toISOString().slice(0,10),now.toISOString(),expiry.toISOString(),row.id);audit(row.institutionId,undefined,"Subscription Activated","Subscription",row.id,{planId:row.planId,orderId,paymentId});db.exec("COMMIT");return getSubscription(row.institutionId);}catch(error){db.exec("ROLLBACK");throw error;}}
export function activateVerifiedSubscription(orderId:string,paymentId:string,signature:string){db.exec("BEGIN IMMEDIATE");try{const row=db.prepare("SELECT id,institution_id AS institutionId,plan_id AS planId,status,razorpay_payment_id AS paymentId FROM subscriptions WHERE razorpay_order_id=?").get(orderId)as{id:string;institutionId:string;planId:string;status:string;paymentId:string|null}|undefined;if(!row)throw new Error("Subscription order not found");if(row.status==="ACTIVE"&&row.paymentId===paymentId){db.exec("COMMIT");return getSubscription(row.institutionId)}const prior=db.prepare("SELECT expiry_date AS expiryDate FROM subscriptions WHERE institution_id=? AND id!=? AND status='ACTIVE' AND expiry_date>? ORDER BY expiry_date DESC LIMIT 1").get(row.institutionId,row.id,new Date().toISOString())as{expiryDate:string}|undefined,now=new Date(),start=prior?new Date(prior.expiryDate):now,expiry=addOneYear(start);db.prepare("UPDATE subscriptions SET status='ACTIVE',activation_date=?,expiry_date=?,razorpay_payment_id=?,razorpay_signature=?,updated_at=CURRENT_TIMESTAMP WHERE id=?").run(now.toISOString(),expiry.toISOString(),paymentId,signature,row.id);db.prepare("INSERT OR IGNORE INTO subscription_payments(id,institution_id,plan,student_capacity,amount,razorpay_payment_id,payment_date,starts_at,ends_at,status)SELECT ?,s.institution_id,p.name,s.student_capacity,s.amount_paid,?,?,?,?,'ACTIVE' FROM subscriptions s JOIN subscription_plans p ON p.id=s.plan_id WHERE s.id=?").run(randomUUID(),paymentId,now.toISOString().slice(0,10),start.toISOString(),expiry.toISOString(),row.id);audit(row.institutionId,undefined,"Subscription Activated","Subscription",row.id,{planId:row.planId,orderId,paymentId,renewal:Boolean(prior)});db.exec("COMMIT");return getSubscription(row.institutionId)}catch(error){db.exec("ROLLBACK");throw error}}
export function findSubscriptionByOrder(orderId:string){return db.prepare("SELECT id,institution_id AS institutionId,plan_id AS planId,amount_paid AS amountPaid,status,razorpay_payment_id AS paymentId FROM subscriptions WHERE razorpay_order_id=?").get(orderId)as{id:string;institutionId:string;planId:string;amountPaid:number;status:string;paymentId:string|null}|undefined;}
export function recordWebhookEvent(id:string,type:string){return db.prepare("INSERT OR IGNORE INTO razorpay_webhook_events(id,event_type)VALUES(?,?)").run(id,type).changes>0;}
export function listSubscriptions(){return db.prepare("SELECT s.id,i.name AS school,p.name AS planName,s.status,s.student_capacity AS studentCapacity,s.amount_paid AS amountPaid,s.activation_date AS activationDate,s.expiry_date AS expiryDate,s.razorpay_order_id AS razorpayOrderId,s.razorpay_payment_id AS razorpayPaymentId,(SELECT COUNT(*) FROM students st WHERE st.institution_id=s.institution_id AND st.status='Active') AS studentUsage FROM subscriptions s JOIN institutions i ON i.id=s.institution_id JOIN subscription_plans p ON p.id=s.plan_id ORDER BY s.created_at DESC").all();}
export function deleteAllRecords(institutionId:string,type:string,userId:string){db.exec("BEGIN IMMEDIATE");try{let count=0;if(type==="students"){count=(db.prepare("SELECT COUNT(*) count FROM students WHERE institution_id=?").get(institutionId)as{count:number}).count;db.prepare("DELETE FROM receipts WHERE institution_id=?").run(institutionId);db.prepare("DELETE FROM payments WHERE institution_id=?").run(institutionId);db.prepare("DELETE FROM fees WHERE institution_id=?").run(institutionId);db.prepare("DELETE FROM attendance WHERE institution_id=?").run(institutionId);db.prepare("DELETE FROM students WHERE institution_id=?").run(institutionId);}else if(type==="teachers")count=Number(db.prepare("DELETE FROM teachers WHERE institution_id=?").run(institutionId).changes);else if(type==="classes")count=Number(db.prepare("DELETE FROM classes WHERE institution_id=?").run(institutionId).changes);else if(type==="attendance"){count=Number(db.prepare("DELETE FROM attendance WHERE institution_id=?").run(institutionId).changes);db.prepare("UPDATE students SET attendance=100,updated_at=CURRENT_TIMESTAMP WHERE institution_id=?").run(institutionId);}else if(type==="fees"||type==="reports"){count=(db.prepare("SELECT COUNT(*) count FROM fees WHERE institution_id=?").get(institutionId)as{count:number}).count;db.prepare("DELETE FROM receipts WHERE institution_id=?").run(institutionId);db.prepare("DELETE FROM payments WHERE institution_id=?").run(institutionId);db.prepare("DELETE FROM fees WHERE institution_id=?").run(institutionId);db.prepare("UPDATE students SET total_fee=0,paid_fee=0,pending_fee=0,fee='Paid',updated_at=CURRENT_TIMESTAMP WHERE institution_id=?").run(institutionId);}else if(type==="payments"){count=(db.prepare("SELECT COUNT(*) count FROM payments WHERE institution_id=?").get(institutionId)as{count:number}).count;db.prepare("DELETE FROM receipts WHERE institution_id=?").run(institutionId);db.prepare("DELETE FROM payments WHERE institution_id=?").run(institutionId);db.prepare("UPDATE fees SET paid_amount=0,pending_amount=final_amount,status=CASE WHEN due_date<date('now') THEN 'Overdue' ELSE 'Pending' END,updated_at=CURRENT_TIMESTAMP WHERE institution_id=?").run(institutionId);db.prepare("UPDATE students SET paid_fee=0,pending_fee=total_fee,fee=CASE WHEN EXISTS(SELECT 1 FROM fees WHERE student_id=students.id AND status='Overdue') THEN 'Overdue' WHEN total_fee=0 THEN 'Paid' ELSE 'Pending' END,updated_at=CURRENT_TIMESTAMP WHERE institution_id=?").run(institutionId);}else if(type==="assignments"||type==="messages")count=Number(db.prepare("DELETE FROM module_records WHERE institution_id=? AND module=?").run(institutionId,type).changes);else throw new Error("Unsupported section");audit(institutionId,userId,"All Records Deleted",type,undefined,{count});activity(institutionId,"delete",`${type} cleared`,`${count} records were deleted`);db.exec("COMMIT");return count;}catch(error){db.exec("ROLLBACK");throw error;}}
export type ModuleRecord={id:string;[key:string]:string};
export function listModuleRecords(institutionId:string,module:string){const rows=db.prepare("SELECT id,data FROM module_records WHERE institution_id=? AND module=? ORDER BY created_at DESC").all(institutionId,module)as unknown as{id:string;data:string}[];return rows.map(row=>({id:row.id,...JSON.parse(row.data)as Record<string,string>}));}
export function addModuleRecord(institutionId:string,module:string,data:Record<string,string>){const record={id:randomUUID(),...data};db.prepare("INSERT INTO module_records(id,institution_id,module,data)VALUES(?,?,?,?)").run(record.id,institutionId,module,JSON.stringify(data));return record;}
