import "server-only";
import { PDFDocument, StandardFonts, rgb, type PDFFont, type PDFImage, type PDFPage } from "pdf-lib";

export type FinancialPdfInput = { title:string; academicYear:string; school:{name:string;address:string;phone:string;email:string;diseCode?:string;website?:string;city?:string;state?:string;pinCode?:string;principalName?:string;registrationNumber?:string;affiliation?:string;motto?:string;schoolType?:string;footerText?:string;logo?:{mimeType:string;data:Uint8Array}}; columns:{key:string;label:string;width:number;align?:"left"|"right"}[]; rows:Record<string,string|number>[]; totals:{label:string;value:string}[];filters?:string[] };
const ink=rgb(.12,.15,.2),muted=rgb(.38,.42,.5),brand=rgb(.25,.12,.58),pale=rgb(.95,.94,.99),line=rgb(.82,.84,.89);

export async function createFinancialReportPdf(input:FinancialPdfInput){
 const doc=await PDFDocument.create(),font=await doc.embedFont(StandardFonts.Helvetica),bold=await doc.embedFont(StandardFonts.HelveticaBold),logo=input.school.logo?(input.school.logo.mimeType==="image/png"?await doc.embedPng(input.school.logo.data):input.school.logo.mimeType==="image/jpeg"?await doc.embedJpg(input.school.logo.data):undefined):undefined;let page=doc.addPage([595.28,841.89]),y=header(page,input,font,bold,logo);const left=38,width=519,rowHeight=22;
 const tableHeader=()=>{page.drawRectangle({x:left,y:y-rowHeight,width,height:rowHeight,color:brand});let x=left;for(const column of input.columns){cell(page,column.label,x+5,y-15,column.width-10,7.2,bold,rgb(1,1,1),column.align);x+=column.width}y-=rowHeight};tableHeader();
 if(!input.rows.length){page.drawText("No records found for the selected academic year.",{x:left+8,y:y-26,size:9,font,color:muted});y-=44}
 for(let index=0;index<input.rows.length;index++){if(y-rowHeight<72){footer(page,doc.getPageCount(),font,input);page=doc.addPage([595.28,841.89]);y=header(page,input,font,bold,logo);tableHeader()}page.drawRectangle({x:left,y:y-rowHeight,width,height:rowHeight,color:index%2?rgb(1,1,1):pale,borderColor:line,borderWidth:.4});let x=left;for(const column of input.columns){cell(page,String(input.rows[index][column.key]??""),x+5,y-15,column.width-10,7.1,font,ink,column.align);x+=column.width}y-=rowHeight}
 y-=10;for(const total of input.totals){if(y<72){footer(page,doc.getPageCount(),font,input);page=doc.addPage([595.28,841.89]);y=header(page,input,font,bold,logo)}const lw=bold.widthOfTextAtSize(total.label,9),vw=bold.widthOfTextAtSize(total.value,9);page.drawText(total.label,{x:557-vw-lw-18,y,size:9,font:bold,color:ink});page.drawText(total.value,{x:557-vw,y,size:9,font:bold,color:brand});y-=17}
 for(let i=0;i<doc.getPageCount();i++)footer(doc.getPage(i),i+1,font,input);return await doc.save();
}
function header(page:PDFPage,input:FinancialPdfInput,font:PDFFont,bold:PDFFont,logo?:PDFImage){const textX=logo?82:38;if(logo)page.drawImage(logo,{x:38,y:782,width:34,height:34});page.drawText(fit(input.school.name.toUpperCase(),bold,17,557-textX),{x:textX,y:802,size:17,font:bold,color:brand});const location=[input.school.address,input.school.city,input.school.state,input.school.pinCode].filter(Boolean).join(", "),details=[location,input.school.diseCode&&`DISE: ${input.school.diseCode}`,input.school.phone,input.school.email,input.school.website].filter(Boolean).join(" | ");page.drawText(fit(details||"School Administration",font,8,557-textX),{x:textX,y:788,size:8,font,color:muted});page.drawLine({start:{x:38,y:778},end:{x:557,y:778},thickness:1,color:line});page.drawText(input.title,{x:38,y:751,size:14,font:bold,color:ink});page.drawText(`Academic Year: ${input.academicYear}`,{x:38,y:735,size:8.5,font,color:muted});const generated=`Generated: ${new Intl.DateTimeFormat("en-IN",{dateStyle:"medium",timeStyle:"short",timeZone:"Asia/Kolkata"}).format(new Date())}`;page.drawText(generated,{x:557-font.widthOfTextAtSize(generated,8.5),y:735,size:8.5,font,color:muted});if(input.filters?.length)page.drawText(fit(`Filters: ${input.filters.join(" | ")}`,font,7.5,519),{x:38,y:720,size:7.5,font,color:muted});return input.filters?.length?701:716}
function cell(page:PDFPage,value:string,x:number,y:number,width:number,size:number,font:PDFFont,color=ink,align:"left"|"right"="left"){const text=fit(value,font,size,width),drawX=align==="right"?x+width-font.widthOfTextAtSize(text,size):x;page.drawText(text,{x:drawX,y,size,font,color})}
function fit(value:string,font:PDFFont,size:number,width:number){let text=value;while(text.length>3&&font.widthOfTextAtSize(text,size)>width)text=text.slice(0,-1);return text===value?text:`${text.slice(0,-3)}...`}
function footer(page:PDFPage,pageNumber:number,font:PDFFont,input:FinancialPdfInput){page.drawLine({start:{x:38,y:42},end:{x:557,y:42},thickness:.5,color:line});const institution=[input.school.footerText,input.school.motto&&`Motto: ${input.school.motto}`,input.school.registrationNumber&&`Reg: ${input.school.registrationNumber}`,input.school.affiliation].filter(Boolean).join(" | ")||"EduLedger - Confidential school document";page.drawText(fit(institution,font,7,450),{x:38,y:28,size:7,font,color:muted});const value=`Page ${pageNumber}`;page.drawText(value,{x:557-font.widthOfTextAtSize(value,7),y:28,size:7,font,color:muted})}
