import { NextResponse } from "next/server";
import * as XLSX from "xlsx";
import { currentUser } from "@/lib/session";
import { accountsSummary,getInstitution,listAccountTransactions,listPayments,logExport } from "@/lib/db";
import { createFinancialReportPdf } from "@/lib/financial-report-pdf";
export const runtime="nodejs";
const roles=["SCHOOL_ADMIN","SUPER_ADMIN","ACCOUNTANT"],reports=["income","expense","fees","salary","monthly-profit-loss","cash-book","academic-year"] as const;type Report=typeof reports[number];
const titles:Record<Report,string>={income:"Income Report",expense:"Expense Report",fees:"Fee Collection Report",salary:"Salary Expense Report","monthly-profit-loss":"Monthly Profit / Loss Report","cash-book":"Cash Book Report","academic-year":"Academic Year Financial Report"};
const money=(value:number)=>`Rs. ${Number(value||0).toLocaleString("en-IN",{minimumFractionDigits:2,maximumFractionDigits:2})}`;

export async function GET(request:Request){
 const user=await currentUser();if(!user)return NextResponse.json({error:"Unauthenticated"},{status:401});if(!roles.includes(user.role))return NextResponse.json({error:"Forbidden"},{status:403});
 const q=new URL(request.url).searchParams,institution=await getInstitution(user.institutionId),requestedYear=q.get("year")||institution.academicYear;if(!/^\d{4}[-–]\d{4}$/.test(requestedYear))return NextResponse.json({error:"Invalid academic year."},{status:400});
 const year=requestedYear.replace("–","-"),requestedReport=q.get("report")||"cash-book";if(!reports.includes(requestedReport as Report))return NextResponse.json({error:"Unsupported financial report."},{status:400});
 const report=requestedReport as Report,format=q.get("format")==="pdf"?"pdf":q.get("format")==="csv"?"csv":"xlsx",built=await buildReport(user.institutionId,report,year,q);await logExport(user.institutionId,user.id,`Accounts ${report}`,built.rows.length);const baseName=`EduLedger_${titles[report].replace(/\s*\/\s*|\s+/g,"_")}_${year}`;
 if(format==="pdf"){try{const data=await createFinancialReportPdf({title:titles[report],academicYear:year,school:institution,...built});return new Response(Buffer.from(data),{headers:{"Content-Type":"application/pdf","Content-Disposition":`inline; filename="${baseName}.pdf"`,"Cache-Control":"private, no-store"}})}catch{return NextResponse.json({error:"Could not generate the PDF report."},{status:500})}}
 const sheet=XLSX.utils.json_to_sheet(built.exportRows),book=XLSX.utils.book_new();XLSX.utils.book_append_sheet(book,sheet,"Accounts");const data=format==="csv"?XLSX.utils.sheet_to_csv(sheet):XLSX.write(book,{type:"buffer",bookType:"xlsx"});return new Response(data,{headers:{"Content-Type":format==="csv"?"text/csv; charset=utf-8":"application/vnd.openxmlformats-officedocument.spreadsheetml.sheet","Content-Disposition":`attachment; filename="${baseName}.${format}"`,"Cache-Control":"private, no-store"}})
}

async function buildReport(institutionId:string,report:Report,year:string,q:URLSearchParams){
 if(report==="fees"){
  const payments=await listPayments(institutionId,{academicYear:year,status:"Success",className:q.get("class")||undefined,section:q.get("section")||undefined,method:q.get("method")||undefined,from:q.get("from")||undefined,to:q.get("to")||undefined,limit:10000});const rows=payments.map(p=>({date:String(p.paymentDate).slice(0,10),student:p.studentName,admission:p.admission,class:`${p.className}-${p.section}`,receipt:p.receiptNumber,particular:p.feeType,mode:p.method,amount:money(p.amount),balance:money(p.remainingBalance)}));
  return{rows,exportRows:rows,columns:[{key:"date",label:"Date",width:55},{key:"student",label:"Student",width:86},{key:"admission",label:"Admission",width:62},{key:"class",label:"Class",width:42},{key:"receipt",label:"Receipt",width:75},{key:"particular",label:"Particular",width:70},{key:"mode",label:"Mode",width:49},{key:"amount",label:"Amount",width:80,align:"right" as const}],totals:[{label:"Total Collection",value:money(payments.reduce((sum,p)=>sum+Number(p.amount),0))}]};
 }
 if(report==="monthly-profit-loss"||report==="academic-year"){
  const summary=await accountsSummary(institutionId,year);if(report==="monthly-profit-loss"){const rows=summary.monthly.map(x=>({month:x.label,fees:money(x.feeCollections/100),income:money(x.income/100),expenses:money(x.expenses/100),net:money(x.net/100)}));return{rows,exportRows:rows,columns:[{key:"month",label:"Month",width:95},{key:"fees",label:"Fee Collection",width:106,align:"right" as const},{key:"income",label:"Total Income",width:106,align:"right" as const},{key:"expenses",label:"Expenses",width:106,align:"right" as const},{key:"net",label:"Net",width:106,align:"right" as const}],totals:[{label:"Net Profit / Loss",value:money(summary.netProfitLoss/100)}]}}
  const rows=[{category:"Fee Expected",amount:money(summary.feeExpected/100)},{category:"Fee Collected",amount:money(summary.totalCollected/100)},{category:"Other / Cash Book Income",amount:money((summary.totalIncome-summary.totalCollected)/100)},{category:"Staff Salaries",amount:money(summary.expenditureStreams.staffSalaries/100)},{category:"Other Expenses",amount:money((summary.totalExpenses-summary.expenditureStreams.staffSalaries)/100)}];return{rows,exportRows:rows,columns:[{key:"category",label:"Financial Summary",width:339},{key:"amount",label:"Amount",width:180,align:"right" as const}],totals:[{label:"Total Income",value:money(summary.totalIncome/100)},{label:"Total Expenses",value:money(summary.totalExpenses/100)},{label:"Net Result",value:money(summary.netProfitLoss/100)}]};
 }
 const type=report==="income"?"income":report==="expense"||report==="salary"?"expense":q.get("type")||undefined,category=report==="salary"?"Staff Salaries":q.get("category")||undefined,result=await listAccountTransactions(institutionId,{academicYear:year,type,category,method:q.get("method")||undefined,from:q.get("from")||undefined,to:q.get("to")||undefined,limit:10000,offset:0}),items=result.items as Record<string,unknown>[];let balance=0;const ordered=report==="cash-book"?[...items].reverse():items,rows=ordered.map(item=>{const amount=Number(item.amountPaise)/100,isIncome=item.transactionType==="income";balance+=isIncome?amount:-amount;return{date:String(item.transactionDate).slice(0,10),description:String(item.description),category:String(item.category),mode:String(item.paymentMethod),reference:String(item.referenceNumber||"-"),cashIn:isIncome?money(amount):"-",cashOut:isIncome?"-":money(amount),balance:money(balance),amount:money(amount)}}),total=items.reduce((sum,item)=>sum+Number(item.amountPaise)/100,0),cashIn=items.filter(x=>x.transactionType==="income").reduce((sum,x)=>sum+Number(x.amountPaise)/100,0),cashOut=items.filter(x=>x.transactionType==="expense").reduce((sum,x)=>sum+Number(x.amountPaise)/100,0);
 if(report==="cash-book")return{rows,exportRows:rows,columns:[{key:"date",label:"Date",width:58},{key:"description",label:"Description",width:126},{key:"reference",label:"Reference",width:72},{key:"mode",label:"Mode",width:55},{key:"cashIn",label:"Cash In",width:69,align:"right" as const},{key:"cashOut",label:"Cash Out",width:69,align:"right" as const},{key:"balance",label:"Balance",width:70,align:"right" as const}],totals:[{label:"Total Cash In",value:money(cashIn)},{label:"Total Cash Out",value:money(cashOut)},{label:"Closing Balance",value:money(cashIn-cashOut)}]};
 return{rows,exportRows:rows,columns:[{key:"date",label:"Date",width:60},{key:"description",label:"Description",width:135},{key:"category",label:"Category",width:85},{key:"mode",label:"Payment Mode",width:70},{key:"reference",label:"Reference",width:89},{key:"amount",label:"Amount",width:80,align:"right" as const}],totals:[{label:report==="income"?"Total Income":report==="salary"?"Total Salary Expense":"Total Expenses",value:money(total)}]};
}
