import {NextResponse} from "next/server";
import {z} from "zod";
import {privateAdmin} from "@/lib/admin-auth";
import {adminAuditLogs,adminOverview,adminSchools,adminSetSchoolStatus,adminSetUserStatus,adminSubscriptions,adminTransactions,adminUsers,databaseHealth,getAdminSettings,saveAdminSettings} from "@/lib/db";
export const runtime="nodejs";
const settingsSchema=z.object({applicationName:z.string().trim().min(2).max(80),supportEmail:z.string().trim().email().or(z.literal("")),currency:z.string().trim().min(3).max(3),timezone:z.string().trim().min(2).max(80),dateFormat:z.string().trim().min(4).max(20),sessionTimeoutMinutes:z.number().int().min(15).max(43200)});
function filters(request:Request){const q=new URL(request.url).searchParams;return{search:q.get("search")||undefined,status:q.get("status")||undefined,school:q.get("school")||undefined,from:q.get("from")||undefined,to:q.get("to")||undefined,limit:Number(q.get("limit"))||50,offset:Number(q.get("offset"))||0}}
export async function GET(request:Request){const admin=await privateAdmin();if(!admin)return NextResponse.json({error:"Private admin authorization required."},{status:403});const q=new URL(request.url).searchParams,section=q.get("section")||"overview",f=filters(request);try{if(section==="overview"||section==="analytics"||section==="notifications")return NextResponse.json(await adminOverview(f));if(section==="users"||section==="accounts")return NextResponse.json(await adminUsers(f));if(section==="schools")return NextResponse.json(await adminSchools(f));if(section==="finance"||section==="transactions")return NextResponse.json(await adminTransactions(f));if(section==="refunds")return NextResponse.json(await adminTransactions({...f,status:"Refunded"}));if(section==="subscriptions")return NextResponse.json({items:await adminSubscriptions()});if(section==="audit")return NextResponse.json({items:await adminAuditLogs(200)});if(section==="settings"||section==="security")return NextResponse.json(await getAdminSettings());if(section==="profile")return NextResponse.json({name:admin.name,email:admin.email,role:admin.role,status:"Active",institutionId:admin.institutionId});if(section==="health"){const started=Date.now();await databaseHealth();return NextResponse.json({backend:"Operational",database:"Connected",authentication:"Operational",server:"Operational",paymentGateway:process.env.RAZORPAY_KEY_ID&&process.env.RAZORPAY_KEY_SECRET?"Configured":"Not configured",emailService:process.env.SMTP_HOST?"Configured":"Not configured",storageService:"Local storage",environment:process.env.NODE_ENV||"development",applicationVersion:process.env.npm_package_version||"1.0.0",uptimeSeconds:Math.round(process.uptime()),apiLatencyMs:Date.now()-started,checkedAt:new Date().toISOString()})}return NextResponse.json({error:"Unknown admin section"},{status:404})}catch{return NextResponse.json({error:"Admin data could not be loaded."},{status:500})}}
export async function PATCH(request:Request){const admin=await privateAdmin();if(!admin)return NextResponse.json({error:"Private admin authorization required."},{status:403});const body=await request.json().catch(()=>null),schema=z.discriminatedUnion("type",[z.object({type:z.literal("user-status"),id:z.string().min(1),status:z.enum(["Active","Inactive","Suspended"])}),z.object({type:z.literal("school-status"),id:z.string().min(1),status:z.enum(["Active","Inactive","Suspended"])}),z.object({type:z.literal("settings"),settings:settingsSchema})]),parsed=schema.safeParse(body);if(!parsed.success)return NextResponse.json({error:"Invalid admin update."},{status:400});try{if(parsed.data.type==="user-status")await adminSetUserStatus(admin.id,parsed.data.id,parsed.data.status);else if(parsed.data.type==="school-status")await adminSetSchoolStatus(admin.id,parsed.data.id,parsed.data.status);else return NextResponse.json({settings:await saveAdminSettings(admin.id,parsed.data.settings)});return NextResponse.json({ok:true})}catch(error){return NextResponse.json({error:error instanceof Error?error.message:"Update failed."},{status:409})}}
