import {NextResponse} from "next/server";
import {deleteStudent,getStudent,updateStudent} from "@/lib/db";
import {currentUser} from "@/lib/session";
import {z} from "zod";
const studentInputSchema=z.object({name:z.string().trim().min(2).max(100),admission:z.string().trim().min(2).max(40),gender:z.enum(["Male","Female","Other"]),dateOfBirth:z.string().min(10),className:z.string().trim().min(1).max(40),section:z.string().trim().min(1).max(10),rollNumber:z.string().trim().max(30),parent:z.string().trim().min(2).max(100),parentPhone:z.string().trim(),parentEmail:z.string().trim(),address:z.string().trim(),admissionDate:z.string().min(10),totalFee:z.coerce.number().min(0),academicYear:z.string(),dueDate:z.string()});
export const runtime="nodejs";
export async function GET(_:Request,{params}:{params:Promise<{id:string}>}){const user=await currentUser();if(!user)return NextResponse.json({error:"Unauthenticated"},{status:401});const{id}=await params,student=getStudent(user.institutionId,id);return student?NextResponse.json({student}):NextResponse.json({error:"Student not found"},{status:404});}
export async function PUT(request:Request,{params}:{params:Promise<{id:string}>}){const user=await currentUser();if(!user)return NextResponse.json({error:"Unauthenticated"},{status:401});if(!["SCHOOL_ADMIN","SUPER_ADMIN","STAFF"].includes(user.role))return NextResponse.json({error:"Forbidden"},{status:403});const parsed=studentInputSchema.partial().safeParse(await request.json().catch(()=>null));if(!parsed.success)return NextResponse.json({error:parsed.error.issues[0]?.message||"Invalid student details"},{status:400});try{return NextResponse.json({student:updateStudent(user.institutionId,(await params).id,parsed.data,user.id)});}catch{return NextResponse.json({error:"Could not update the student."},{status:400});}}
export async function DELETE(_:Request,{params}:{params:Promise<{id:string}>}){const user=await currentUser();if(!user)return NextResponse.json({error:"Unauthenticated"},{status:401});if(!["SCHOOL_ADMIN","SUPER_ADMIN"].includes(user.role))return NextResponse.json({error:"Forbidden"},{status:403});try{return deleteStudent(user.institutionId,(await params).id,user.id)?new NextResponse(null,{status:204}):NextResponse.json({error:"Student not found"},{status:404});}catch(error){return NextResponse.json({error:error instanceof Error?error.message:"Could not delete student"},{status:409});}}
