import { z } from "zod";
import { currentUser } from "@/lib/session";
import { listPromotionHistory,promoteStudents,promotionCandidates,promotionOptions,studentAcademicHistory,validatePromotion } from "@/lib/db";
import { logServerError } from "@/lib/server-errors";
export const runtime="nodejs";
const schema=z.object({action:z.enum(["validate","confirm"]),sourceYear:z.string().min(4).max(20),targetYear:z.string().min(4).max(20),sourceClass:z.string().min(1).max(50),sourceSection:z.string().max(20),targetClass:z.string().min(1).max(50),targetSection:z.string().max(20),studentIds:z.array(z.string().min(1)).min(1).max(2000)});
const allowed=(role:string)=>["SCHOOL_ADMIN","SUPER_ADMIN"].includes(role);
export async function GET(request:Request){const user=await currentUser();if(!user)return Response.json({error:"Unauthenticated"},{status:401});if(!allowed(user.role))return Response.json({error:"Forbidden"},{status:403});const q=new URL(request.url).searchParams,mode=q.get("mode")||"options";if(mode==="candidates")return Response.json({students:await promotionCandidates(user.institutionId,q.get("sourceYear")||"",q.get("sourceClass")||"",q.get("sourceSection")||"")});if(mode==="history")return Response.json({history:await listPromotionHistory(user.institutionId,q.get("search")||"")});if(mode==="student-history")return Response.json({history:await studentAcademicHistory(user.institutionId,q.get("studentId")||"")});return Response.json(await promotionOptions(user.institutionId));}
export async function POST(request:Request){const user=await currentUser();if(!user)return Response.json({error:"Unauthenticated"},{status:401});if(!allowed(user.role))return Response.json({error:"Forbidden"},{status:403});const parsed=schema.safeParse(await request.json().catch(()=>null));if(!parsed.success)return Response.json({error:parsed.error.issues[0]?.message||"Invalid promotion request."},{status:400});const {action,...input}=parsed.data;try{if(action==="validate")return Response.json({preview:await validatePromotion(user.institutionId,input)});return Response.json(await promoteStudents(user.institutionId,user.id,input),{status:201});}catch(error){logServerError("student-promotion",error);const message=error instanceof Error&&(/already|validation|belong|eligible/i.test(error.message))?error.message:"Unable to promote students. No changes were saved.";return Response.json({error:message},{status:409})}}
