export type ModuleConfig={title:string;description:string;action:string;fields:{key:string;label:string;placeholder:string}[];metrics:[string,string][];defaults:Record<string,string>[];comingSoon?:boolean};
export const moduleConfigs:Record<string,ModuleConfig>={
 teachers:{title:"Teachers",description:"Manage faculty profiles, subjects and class assignments.",action:"Add teacher",fields:[{key:"name",label:"Teacher name",placeholder:"Meera Iyer"},{key:"employee",label:"Employee ID",placeholder:"EMP-1042"},{key:"subject",label:"Primary subject",placeholder:"Mathematics"},{key:"classes",label:"Assigned classes",placeholder:"9-A, 10-B"}],metrics:[["Total teachers","142"],["Present today","136"],["On leave","6"],["Departments","12"]],defaults:[{name:"Meera Iyer",employee:"EMP-1008",subject:"Mathematics",classes:"9-A, 10-B"},{name:"Rahul Verma",employee:"EMP-1012",subject:"Physics",classes:"11-A, 12-A"},{name:"Sara Khan",employee:"EMP-1021",subject:"English",classes:"7-B, 8-A"}]},
 classes:{title:"Classes & Sections",description:"Organize classes, sections, rooms and class teachers.",action:"Create class",fields:[{key:"name",label:"Class",placeholder:"Class 7"},{key:"section",label:"Section",placeholder:"A"},{key:"teacher",label:"Class teacher",placeholder:"Meera Iyer"},{key:"room",label:"Room",placeholder:"Room 204"}],metrics:[["Classes","12"],["Sections","28"],["Rooms in use","26"],["Average size","34"]],defaults:[{name:"Class 10",section:"A",teacher:"Meera Iyer",room:"Room 301"},{name:"Class 8",section:"B",teacher:"Sara Khan",room:"Room 206"},{name:"Class 6",section:"C",teacher:"Arjun Das",room:"Room 104"}]},
 payments:{title:"Fees & Payments",description:"Track collections, outstanding balances and verified transactions.",action:"Record payment",fields:[{key:"student",label:"Student",placeholder:"Ananya Mehta"},{key:"transaction",label:"Transaction ID",placeholder:"pay_R7K42"},{key:"amount",label:"Amount",placeholder:"₹24,500"},{key:"status",label:"Status",placeholder:"Paid"}],metrics:[["Collected","₹8.4L"],["Pending","₹4.2L"],["Paid invoices","318"],["Collection rate","86%"]],defaults:[{student:"Ananya Mehta",transaction:"pay_R7K42",amount:"₹24,500",status:"Paid"},{student:"Arjun Nair",transaction:"pay_R7J91",amount:"₹18,000",status:"Paid"},{student:"Riya Singh",transaction:"INV-24038",amount:"₹21,500",status:"Overdue"}]},
 messages:{title:"Messages",description:"Keep school communication organized and accountable.",action:"New message",fields:[{key:"recipient",label:"Recipient",placeholder:"Parents · Class 8-B"},{key:"subject",label:"Subject",placeholder:"Parent meeting"},{key:"message",label:"Message",placeholder:"Meeting begins at 10:00 AM"},{key:"status",label:"Status",placeholder:"Sent"}],metrics:[["Unread","8"],["Sent today","24"],["Parent replies","12"],["Announcements","3"]],defaults:[{recipient:"Parents · Class 10-A",subject:"Mid-term schedule",message:"Schedule and instructions shared",status:"Read"},{recipient:"Faculty",subject:"Staff briefing",message:"Friday at 3:30 PM",status:"Sent"}]},
 settings:{title:"Settings",description:"Manage institution preferences, security and notifications.",action:"Add preference",fields:[{key:"setting",label:"Setting",placeholder:"Academic year"},{key:"value",label:"Value",placeholder:"2026–27"},{key:"category",label:"Category",placeholder:"Institution"},{key:"status",label:"Status",placeholder:"Active"}],metrics:[["Users","18"],["Active sessions","3"],["Integrations","2"],["Security score","Good"]],defaults:[{setting:"Academic year",value:"2026–27",category:"Institution",status:"Active"},{setting:"Fee reminders",value:"3 days before due date",category:"Notifications",status:"Active"},{setting:"Two-factor authentication",value:"Optional",category:"Security",status:"Available"}]}
};
const placeholder=(title:string,description:string):ModuleConfig=>({title,description,action:`Open ${title}`,fields:[{key:"name",label:"Name",placeholder:title}],metrics:[],defaults:[],comingSoon:true});
Object.assign(moduleConfigs,{"salary-management":placeholder("Salary Management","Manage staff payroll, deductions and salary statements."),accounts:placeholder("Accounts","Review ledgers, balances and accounting records."),"cash-book":placeholder("Cash Book","Track daily cash receipts and payments."),"audit-log":placeholder("Audit Log","Review secure administrative activity across EduLedger.")});
export const supportedModules=Object.keys(moduleConfigs);
