"use client";
import Link from "next/link";
import { useCallback,useEffect,useMemo,useState } from "react";
import { ArrowLeft,BookOpen,CalendarCheck,Download,IndianRupee,Layers3,Loader2,Plus,Trash2,Users } from "lucide-react";

const tabs=["Overview","Students","Teachers","Attendance","Fees","Timetable","Exams & Results","Reports","Settings"] as const;
type Tab=typeof tabs[number];
type Workspace={summary:{name:string;slug:string;description:string;academicYear:string;studentCount:number;teacherCount:number;classTeacher:string;sectionCount:number};sections:{id:string;section:string;teacher:string;capacity:number;status:string}[];students:{id:string;name:string;admission:string;section:string;rollNumber:string;parent:string;parentPhone:string;attendance:number;fee:string;pendingFee:number;status:string}[];teachers:{id:string;name:string;employeeId:string;subject:string;classes:string;phone:string;email:string;joiningDate:string;status:string}[];attendance:{id:string;date:string;studentName:string;section:string;status:string}[];fees:{id:string;studentName:string;admission:string;section:string;totalAmount:number;paidAmount:number;pendingAmount:number;status:string}[];payments:{id:string;studentName:string;receiptNumber:string;amount:number;paymentDate:string}[];timetable:{id:string;section:string;subject:string;weekday:number;startTime:string;endTime:string;teacherName:string}[];exams:{id:string;name:string;examDate:string;section:string;subject:string;maxMarks:number;passingMarks:number}[];results:{id:string;examId:string;studentName:string;subject:string;marks:number;grade:string;status:string}[];metrics:{present:number;absent:number;totalFees:number;paidFees:number;pendingFees:number}};
const money=(n:number)=>new Intl.NumberFormat("en-IN",{style:"currency",currency:"INR",maximumFractionDigits:0}).format(n);
const days=["","Monday","Tuesday","Wednesday","Thursday","Friday","Saturday"];

export function ClassWorkspace({slug}:{slug:string}){
 const[data,setData]=useState<Workspace|null>(null),[tab,setTab]=useState<Tab>("Overview"),[loading,setLoading]=useState(true),[message,setMessage]=useState(""),[modal,setModal]=useState<"section"|"timetable"|"exam"|"result"|null>(null);
 const load=useCallback(async()=>{setLoading(true);const r=await fetch(`/api/classes/${slug}`),j=await r.json();if(r.ok)setData(j);else setMessage(j.error);setLoading(false)},[slug]);useEffect(()=>{void load()},[load]);
 async function submit(e:React.FormEvent<HTMLFormElement>){e.preventDefault();const body=Object.fromEntries(new FormData(e.currentTarget));body.action=modal!;if(modal!=="result")body.academicYear=data!.summary.academicYear;const r=await fetch(`/api/classes/${slug}`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(body)}),j=await r.json();if(!r.ok)return setMessage(j.error);setModal(null);setMessage("Saved successfully.");await load()}
 async function removeSection(id:string){if(!confirm("Delete this section? Active student records will prevent deletion."))return;const r=await fetch(`/api/classes/${slug}?sectionId=${id}`,{method:"DELETE"}),j=await r.json();setMessage(r.ok?"Section deleted.":j.error);if(r.ok)await load()}
 if(loading)return <div className="grid min-h-[60vh] place-items-center"><Loader2 className="animate-spin text-brand"/></div>;if(!data)return <p className="card p-8">{message||"Class not found."}</p>;
 const s=data.summary,metrics=[["Total students",s.studentCount,Users],["Total teachers",s.teacherCount,Users],["Present today",data.metrics.present,CalendarCheck],["Absent today",data.metrics.absent,CalendarCheck],["Total fees",money(data.metrics.totalFees),IndianRupee],["Paid fees",money(data.metrics.paidFees),IndianRupee],["Pending fees",money(data.metrics.pendingFees),IndianRupee]] as const;
 return <div className="mx-auto max-w-[1500px]"><Link href="/dashboard/classes" className="mb-5 inline-flex items-center gap-2 text-sm font-bold text-muted hover:text-ink"><ArrowLeft className="size-4"/>All classes</Link><header className="relative overflow-hidden rounded-[1.75rem] border bg-gradient-to-br from-brand/15 via-panel to-blue-500/10 p-6 shadow-sm sm:p-8"><div className="absolute -right-16 -top-20 size-64 rounded-full bg-brand/15 blur-3xl"/><div className="relative flex flex-col justify-between gap-6 md:flex-row md:items-end"><div><span className="grid size-14 place-items-center rounded-2xl bg-brand text-white shadow-lg"><BookOpen/></span><h1 className="mt-5 text-3xl font-black sm:text-4xl">{s.name}</h1><p className="mt-1 text-muted">{s.description} · Academic Year {s.academicYear}</p><p className="mt-3 text-sm"><span className="text-muted">Class teacher:</span> <b>{s.classTeacher}</b></p></div><div className="grid grid-cols-2 gap-3 text-sm sm:grid-cols-3"><Mini label="Students" value={s.studentCount}/><Mini label="Sections" value={s.sectionCount}/><Mini label="Teachers" value={s.teacherCount}/></div></div></header>{message&&<p className="mt-4 rounded-xl border bg-panel p-3 text-sm">{message}</p>}
 <nav className="mt-6 flex gap-1 overflow-x-auto rounded-2xl border bg-panel p-1.5">{tabs.map(item=><button key={item} onClick={()=>setTab(item)} className={`whitespace-nowrap rounded-xl px-4 py-2.5 text-sm font-bold transition ${tab===item?"bg-ink text-canvas shadow":"text-muted hover:bg-canvas"}`}>{item}</button>)}</nav>
 <div className="mt-5">{tab==="Overview"&&<><section className="grid grid-cols-2 gap-3 lg:grid-cols-4">{metrics.map(([label,value,Icon])=><article className="card p-5" key={label}><Icon className="size-5 text-brand"/><p className="mt-4 text-sm text-muted">{label}</p><b className="mt-1 block text-2xl">{value}</b></article>)}</section><section className="card mt-5 p-6"><h2 className="text-lg font-bold">Sections overview</h2><SectionCards data={data} remove={removeSection}/></section></>}
 {tab==="Students"&&<Panel title={`${s.name} students`} action={<Link className="btn-primary" href={`/dashboard/students?class=${encodeURIComponent(s.name)}&add=1`}><Plus className="size-4"/>Add student</Link>}><Table heads={["Student","Admission","Section","Roll no.","Parent","Attendance","Fee status"]} rows={data.students.map(x=>[x.name,x.admission,x.section,x.rollNumber||"—",`${x.parent} · ${x.parentPhone||"No phone"}`,`${x.attendance}%`,x.fee])}/></Panel>}
 {tab==="Teachers"&&<Panel title="Assigned teachers" action={<Link href="/dashboard/teachers" className="btn-primary"><Plus className="size-4"/>Assign teacher</Link>}><Table heads={["Teacher","ID","Subject","Assigned classes","Phone","Email","Status"]} rows={data.teachers.filter(t=>t.classes.includes(s.name)).map(t=>[t.name,t.employeeId,t.subject,t.classes,t.phone,t.email,t.status])}/></Panel>}
 {tab==="Attendance"&&<Panel title="Class-wise attendance" action={<><a className="btn-secondary" href={`/api/export?type=attendance&format=csv&class=${encodeURIComponent(s.name)}`}><Download className="size-4"/>CSV</a><Link className="btn-primary" href={`/dashboard/attendance?class=${encodeURIComponent(s.name)}`}>Mark attendance</Link></>}><Table heads={["Date","Student","Section","Status"]} rows={data.attendance.map(x=>[x.date.slice(0,10),x.studentName,x.section,x.status])}/></Panel>}
 {tab==="Fees"&&<Panel title="Class-wise fees" action={<Link className="btn-primary" href={`/dashboard/payments?class=${encodeURIComponent(s.name)}`}>Open payments</Link>}><div className="mb-5 grid gap-3 sm:grid-cols-3"><Mini label="Total" value={money(data.metrics.totalFees)}/><Mini label="Paid" value={money(data.metrics.paidFees)}/><Mini label="Pending" value={money(data.metrics.pendingFees)}/></div><Table heads={["Student","Admission","Section","Total","Paid","Remaining","Status"]} rows={data.fees.map(x=>[x.studentName,x.admission,x.section,money(x.totalAmount),money(x.paidAmount),money(x.pendingAmount),x.status])}/><h3 className="mt-7 font-bold">Recent payments</h3><Table heads={["Student","Receipt","Amount","Date"]} rows={data.payments.slice(0,8).map(x=>[x.studentName,x.receiptNumber,money(x.amount),x.paymentDate])}/></Panel>}
 {tab==="Timetable"&&<Panel title={`${s.name} timetable`} action={<button className="btn-primary" onClick={()=>setModal("timetable")}><Plus className="size-4"/>Add entry</button>}><Table heads={["Day","Time","Section","Subject","Teacher"]} rows={data.timetable.map(x=>[days[x.weekday],`${x.startTime} – ${x.endTime}`,x.section,x.subject,x.teacherName])}/></Panel>}
 {tab==="Exams & Results"&&<Panel title="Exams & results" action={<><button className="btn-secondary" onClick={()=>setModal("result")}>Add result</button><button className="btn-primary" onClick={()=>setModal("exam")}><Plus className="size-4"/>Create exam</button></>}><Table heads={["Exam","Date","Section","Subject","Max","Pass"]} rows={data.exams.map(x=>[x.name,x.examDate,x.section,x.subject,x.maxMarks,x.passingMarks])}/><h3 className="mt-7 font-bold">Student results</h3><Table heads={["Student","Subject","Marks","Grade","Result"]} rows={data.results.map(x=>[x.studentName,x.subject,x.marks,x.grade,x.status])}/></Panel>}
 {tab==="Reports"&&<Reports name={s.name}/>} {tab==="Settings"&&<Panel title="Sections & class settings" action={<button className="btn-primary" onClick={()=>setModal("section")}><Plus className="size-4"/>Add section</button>}><SectionCards data={data} remove={removeSection}/></Panel>}</div>
 {modal&&<RecordModal kind={modal} data={data} close={()=>setModal(null)} submit={submit}/>}</div>
}
function Mini({label,value}:{label:string;value:string|number}){return <div className="rounded-2xl border bg-panel/70 p-4"><span className="text-xs text-muted">{label}</span><b className="mt-1 block">{value}</b></div>}
function Panel({title,action,children}:{title:string;action?:React.ReactNode;children:React.ReactNode}){return <section className="card overflow-hidden"><div className="flex flex-wrap items-center justify-between gap-3 border-b p-5"><h2 className="text-lg font-bold">{title}</h2><div className="flex gap-2">{action}</div></div><div className="p-5">{children}</div></section>}
function Table({heads,rows}:{heads:string[];rows:(string|number)[][]}){return <div className="overflow-x-auto"><table className="w-full whitespace-nowrap text-left text-sm"><thead className="bg-canvas text-xs uppercase text-muted"><tr>{heads.map(h=><th className="px-4 py-3" key={h}>{h}</th>)}</tr></thead><tbody className="divide-y">{rows.map((r,i)=><tr key={i}>{r.map((v,j)=><td className={`px-4 py-3 ${j===0?"font-bold":""}`} key={j}>{v}</td>)}</tr>)}</tbody></table>{!rows.length&&<p className="p-10 text-center text-sm text-muted">No records for this class yet.</p>}</div>}
function SectionCards({data,remove}:{data:Workspace;remove:(id:string)=>void}){return <div className="mt-4 grid gap-3 md:grid-cols-2 xl:grid-cols-3">{data.sections.map(x=><article className="rounded-2xl border bg-canvas p-4" key={x.id}><div className="flex justify-between"><div><b>Section {x.section}</b><p className="text-xs text-muted">{x.teacher||"Teacher not assigned"}</p></div><button className="icon-btn text-red-600" onClick={()=>remove(x.id)}><Trash2/></button></div><div className="mt-4 flex justify-between text-sm"><span>{data.students.filter(s=>s.section===x.section).length} students</span><span>Capacity {x.capacity}</span></div></article>)}</div>}
function Reports({name}:{name:string}){const reports=[["Student list","students"],["Attendance report","attendance"],["Fee collection report","fees"],["Pending fees report","fees"],["Teacher report","teachers"],["Class strength report","classes"]];return <Panel title="Class reports"><div className="grid gap-3 md:grid-cols-2 xl:grid-cols-3">{reports.map(([label,type])=><article className="rounded-2xl border bg-canvas p-4" key={label}><b>{label}</b><p className="mt-1 text-xs text-muted">Filtered to {name}</p><div className="mt-4 flex gap-2"><a className="btn-secondary !px-3 !py-2" href={`/api/export?type=${type}&format=csv&class=${encodeURIComponent(name)}`}>CSV</a><a className="btn-primary !px-3 !py-2" href={`/api/export?type=${type}&format=xlsx&class=${encodeURIComponent(name)}`}>Excel</a></div></article>)}</div></Panel>}
function RecordModal({kind,data,close,submit}:{kind:"section"|"timetable"|"exam"|"result";data:Workspace;close:()=>void;submit:(e:React.FormEvent<HTMLFormElement>)=>void}){return <div className="fixed inset-0 z-[70] grid place-items-center bg-black/50 p-4"><form onSubmit={submit} className="card max-h-[90vh] w-full max-w-xl overflow-y-auto p-7"><div className="flex justify-between"><h2 className="text-xl font-bold">{kind==="section"?"Add section":kind==="timetable"?"Add timetable entry":kind==="exam"?"Create exam":"Add result"}</h2><button type="button" onClick={close}>×</button></div><div className="mt-6 grid gap-4 sm:grid-cols-2">{kind==="section"&&<><Field name="section" label="Section name"/><Field name="teacher" label="Class teacher" required={false}/><Field name="capacity" label="Capacity" type="number" value="40"/></>}{kind==="timetable"&&<><SelectField name="section" label="Section" options={data.sections.map(s=>s.section)}/><Field name="subject" label="Subject"/><SelectField name="teacherId" label="Teacher" options={data.teachers.map(t=>t.id)} labels={data.teachers.map(t=>t.name)}/><SelectField name="weekday" label="Day" options={["1","2","3","4","5","6"]} labels={days.slice(1)}/><Field name="startTime" label="Start time" type="time"/><Field name="endTime" label="End time" type="time"/></>}{kind==="exam"&&<><Field name="name" label="Exam name"/><Field name="examDate" label="Exam date" type="date"/><SelectField name="section" label="Section" options={data.sections.map(s=>s.section)}/><Field name="subject" label="Subject"/><Field name="maxMarks" label="Maximum marks" type="number" value="100"/><Field name="passingMarks" label="Passing marks" type="number" value="35"/></>}{kind==="result"&&<><SelectField name="examId" label="Exam" options={data.exams.map(e=>e.id)} labels={data.exams.map(e=>`${e.name} · ${e.subject}`)}/><SelectField name="studentId" label="Student" options={data.students.map(s=>s.id)} labels={data.students.map(s=>s.name)}/><Field name="marks" label="Marks" type="number"/></>}</div><div className="mt-6 flex justify-end gap-2"><button type="button" className="btn-secondary" onClick={close}>Cancel</button><button className="btn-primary">Save</button></div></form></div>}
function Field({name,label,type="text",value,required=true}:{name:string;label:string;type?:string;value?:string;required?:boolean}){return <label className="text-sm font-bold">{label}<input name={name} type={type} defaultValue={value} required={required} className="mt-2 w-full rounded-xl border bg-canvas px-4 py-3 font-normal"/></label>}
function SelectField({name,label,options,labels}:{name:string;label:string;options:string[];labels?:string[]}){return <label className="text-sm font-bold">{label}<select name={name} required className="mt-2 w-full rounded-xl border bg-canvas px-4 py-3 font-normal"><option value="">Select {label.toLowerCase()}</option>{options.map((o,i)=><option value={o} key={o}>{labels?.[i]||o}</option>)}</select></label>}
