"use client";
import Link from "next/link";
import { useEffect, useMemo, useState } from "react";
import { BookOpen, ChevronRight, GraduationCap, Layers3, Loader2, Search, Users } from "lucide-react";
import type { ElementType } from "react";
type ClassSummary={name:string;slug:string;description:string;academicYear:string;studentCount:number;teacherCount:number;classTeacher:string;sectionCount:number;status:string};
export function Classes(){
 const[classes,setClasses]=useState<ClassSummary[]>([]),[year,setYear]=useState("2026-2027"),[query,setQuery]=useState(""),[loading,setLoading]=useState(true),[error,setError]=useState("");
 useEffect(()=>{fetch(`/api/classes?year=${encodeURIComponent(year)}`).then(async r=>({ok:r.ok,data:await r.json()})).then(({ok,data})=>{if(!ok)throw new Error(data.error);setClasses(data.classes||[]);setYear(data.academicYear||year)}).catch(e=>setError(e.message)).finally(()=>setLoading(false))},[year]);
 const visible=useMemo(()=>classes.filter(c=>(c.name+c.description+c.classTeacher).toLowerCase().includes(query.toLowerCase())),[classes,query]);
 const totals=useMemo(()=>({students:classes.reduce((n,c)=>n+c.studentCount,0),teachers:classes.reduce((n,c)=>n+c.teacherCount,0),sections:classes.reduce((n,c)=>n+c.sectionCount,0)}),[classes]);
 return <div className="mx-auto max-w-[1500px]"><div className="flex flex-col justify-between gap-5 lg:flex-row lg:items-end"><div><p className="label">Academics · {year}</p><h1 className="mt-2 text-3xl font-black sm:text-4xl">Classes Management</h1><p className="mt-2 max-w-3xl text-muted">Manage all school classes, students, teachers, attendance, and academic information in one place.</p></div><label className="flex h-11 min-w-64 items-center gap-2 rounded-xl border bg-panel px-4"><Search className="size-4 text-muted"/><input value={query} onChange={e=>setQuery(e.target.value)} className="w-full bg-transparent text-sm outline-none" placeholder="Search classes..."/></label></div>
 <section className="mt-7 grid grid-cols-2 gap-3 lg:grid-cols-4">{[["Total classes",classes.length,BookOpen],["Total students",totals.students,GraduationCap],["Teacher assignments",totals.teachers,Users],["Total sections",totals.sections,Layers3]].map(([label,value,icon])=><Metric key={String(label)} label={String(label)} value={Number(value)} icon={icon as ElementType}/>)}</section>
 {error&&<p className="mt-5 rounded-xl border border-red-200 bg-red-50 p-4 text-sm text-red-700">{error}</p>}{loading?<div className="grid min-h-96 place-items-center"><Loader2 className="animate-spin text-brand"/></div>:<section className="mt-6 grid gap-5 md:grid-cols-2 xl:grid-cols-3 2xl:grid-cols-4">{visible.map(item=><article key={item.slug} className="group relative overflow-hidden rounded-[1.5rem] border bg-panel p-5 shadow-sm transition duration-300 hover:-translate-y-1 hover:shadow-xl"><div className="absolute -right-10 -top-10 size-36 rounded-full bg-brand/10 blur-2xl transition group-hover:bg-brand/20"/><div className="relative flex items-start justify-between"><span className="grid size-12 place-items-center rounded-2xl bg-gradient-to-br from-brand to-blue-600 text-white shadow-lg shadow-brand/20"><BookOpen className="size-6"/></span><span className="rounded-full border bg-canvas px-2.5 py-1 text-[11px] font-bold text-emerald-600">{item.status}</span></div><div className="relative mt-5"><h2 className="text-xl font-black">{item.name}</h2><p className="mt-1 text-sm text-muted">{item.description}</p><div className="mt-5 grid grid-cols-2 gap-3 rounded-2xl bg-canvas/80 p-3 text-sm"><Stat label="Students" value={item.studentCount}/><Stat label="Teachers" value={item.teacherCount}/><Stat label="Sections" value={item.sectionCount}/><Stat label="Academic year" value={item.academicYear}/></div><div className="mt-4 min-h-10"><p className="text-xs text-muted">Class teacher</p><b className="text-sm">{item.classTeacher}</b></div><Link href={`/dashboard/classes/${item.slug}`} className="btn-primary mt-4 w-full justify-between">View class <ChevronRight className="size-4"/></Link></div></article>)}</section>}{!loading&&!visible.length&&<div className="card mt-6 p-16 text-center"><b>No matching classes</b></div>}</div>;
}
function Stat({label,value}:{label:string;value:string|number}){return <div><span className="text-xs text-muted">{label}</span><b className="block">{value}</b></div>}
function Metric({label,value,icon:Icon}:{label:string;value:number;icon:ElementType}){return <article className="card p-4 sm:p-5"><span className="grid size-10 place-items-center rounded-xl bg-brand/10 text-brand"><Icon className="size-5"/></span><p className="mt-4 text-xs text-muted sm:text-sm">{label}</p><b className="mt-1 block text-2xl">{value}</b></article>}
