"use client";
import Link from "next/link";
import { usePathname,useRouter } from "next/navigation";
import { BookOpen,CalendarDays,ChevronRight,Command,DatabaseBackup,FileClock,GraduationCap,IndianRupee,Landmark,LayoutDashboard,LogOut,Menu,School,Search,Settings,ShieldCheck,Users,WalletCards,WalletMinimal,X } from "lucide-react";
import { useCallback,useState,type ElementType } from "react";
import { Logo } from "./logo";
import { ThemeToggle } from "./theme";
import { SubscriptionModal } from "./subscription-modal";
import type { SubscriptionSummary } from "@/lib/db";

type NavItem={label:string;href:string;icon:ElementType};
const groups:{label:string;items:NavItem[]}[]=[
 {label:"Main",items:[{label:"Dashboard",href:"/dashboard",icon:LayoutDashboard},{label:"Students",href:"/dashboard/students",icon:GraduationCap},{label:"Staff",href:"/dashboard/teachers",icon:Users},{label:"Classes",href:"/dashboard/classes",icon:BookOpen}]},
 {label:"Academics",items:[{label:"Classes & Sections",href:"/dashboard/classes",icon:LayersIcon}]},
 {label:"Finance",items:[{label:"Fees Collection",href:"/dashboard/payments",icon:IndianRupee},{label:"Fee Payments",href:"/dashboard/payment-history",icon:WalletCards},{label:"Fee History",href:"/dashboard/payment-history",icon:FileClock},{label:"Salary Management",href:"/dashboard/salary-management",icon:WalletMinimal},{label:"Financial Reports",href:"/dashboard/accounts/reports",icon:Landmark}]},
 {label:"Management",items:[{label:"Accounts",href:"/dashboard/accounts",icon:Landmark},{label:"Cash Book",href:"/dashboard/cash-book",icon:BookOpen},{label:"Audit Log",href:"/dashboard/audit-log",icon:ShieldCheck},{label:"Settings",href:"/dashboard/settings",icon:Settings}]},
 {label:"Administration",items:[{label:"School Profile",href:"/dashboard/settings",icon:School},{label:"Academic Year",href:"/dashboard/settings",icon:CalendarDays},{label:"Subscription / Plan",href:"/subscription",icon:WalletCards},{label:"Backup & Data Management",href:"/dashboard/import",icon:DatabaseBackup}]},
];
export function Shell({children,user,schoolName,subscription}:{children:React.ReactNode;user:{name:string;role:string};schoolName:string;subscription:SubscriptionSummary}){
 const path=usePathname(),router=useRouter(),[open,setOpen]=useState(false),[loggingOut,setLoggingOut]=useState(false),[activationOpen,setActivationOpen]=useState(false);
 const closeActivation=useCallback(()=>setActivationOpen(false),[]);
 const active=subscription.status==="ACTIVE",initials=user.name.split(" ").map(x=>x[0]).slice(0,2).join("").toUpperCase();
 async function logout(){setLoggingOut(true);await fetch("/api/auth/logout",{method:"POST"});router.replace("/login");router.refresh()}
 function navigate(event:React.MouseEvent<HTMLAnchorElement>,href:string){setOpen(false);if(!active&&href!=="/dashboard"&&href!=="/dashboard/settings"&&href!=="/subscription"){event.preventDefault();setActivationOpen(true)}}
 function selected(href:string){if(href==="/dashboard")return path===href;return path===href||path.startsWith(`${href}/`)}
 return <div className="min-h-screen bg-canvas"><button onClick={()=>setOpen(true)} className="fixed left-4 top-4 z-30 rounded-xl border bg-panel p-2.5 shadow-sm lg:hidden" aria-label="Open navigation"><Menu/></button>{open&&<button className="fixed inset-0 z-40 bg-slate-950/50 backdrop-blur-[2px] lg:hidden" onClick={()=>setOpen(false)} aria-label="Close navigation"/>}
 <aside aria-label="Main navigation" className={`fixed inset-y-0 left-0 z-50 flex w-[280px] flex-col border-r bg-panel shadow-2xl transition-transform duration-300 lg:translate-x-0 lg:shadow-none ${open?"translate-x-0":"-translate-x-full"}`}>
  <div className="border-b px-5 pb-4 pt-5"><div className="flex items-center justify-between"><Logo/><button onClick={()=>setOpen(false)} className="rounded-lg p-2 hover:bg-canvas lg:hidden" aria-label="Close navigation"><X className="size-5"/></button></div><p className="ml-11 -mt-1 text-[10px] font-semibold uppercase tracking-[.16em] text-muted">School Management System</p><div className="mt-5 rounded-2xl border bg-canvas/70 p-3"><p className="truncate text-sm font-bold">{schoolName}</p><p className="mt-0.5 text-xs text-muted">Administrator workspace</p></div>{!active&&<button onClick={()=>setActivationOpen(true)} className="mt-3 w-full rounded-xl bg-violet-600 px-3 py-2.5 text-left text-xs font-bold text-white shadow-sm">Activate subscription <ChevronRight className="float-right size-4"/></button>}</div>
  <nav className="sidebar-scroll flex-1 overflow-y-auto px-3 py-4">{groups.map(group=><section className="mb-5" key={group.label}><h2 className="mb-1.5 px-3 text-[10px] font-extrabold uppercase tracking-[.18em] text-muted/75">{group.label}</h2><div className="space-y-0.5">{group.items.map(({label,href,icon:Icon})=><Link key={`${group.label}-${label}`} href={href} onClick={e=>navigate(e,href)} aria-current={selected(href)?"page":undefined} className={`group flex min-h-10 items-center gap-3 rounded-xl px-3 py-2 text-[13px] font-semibold transition-all ${selected(href)?"bg-violet-600 text-white shadow-md shadow-violet-500/20":"text-muted hover:bg-violet-50 hover:text-violet-700 dark:hover:bg-violet-500/10 dark:hover:text-violet-300"}`}><Icon className={`size-[17px] shrink-0 ${selected(href)?"text-white":"text-muted group-hover:text-violet-600"}`}/><span className="truncate">{label}</span></Link>)}</div></section>)}</nav>
  <div className="border-t bg-panel p-3"><div className="flex items-center gap-3 rounded-2xl bg-canvas/70 p-3"><span className="grid size-10 shrink-0 place-items-center rounded-xl bg-gradient-to-br from-violet-500 to-indigo-600 text-sm font-black text-white shadow-sm">{initials}</span><div className="min-w-0 flex-1"><b className="block truncate text-sm">{user.name}</b><span className="block text-[11px] capitalize text-muted">{user.role.toLowerCase().replaceAll("_"," ")}</span></div><Link href="/dashboard/settings" onClick={e=>navigate(e,"/dashboard/settings")} className="rounded-lg p-2 text-muted hover:bg-panel hover:text-violet-600" aria-label="Settings"><Settings className="size-4"/></Link></div><button disabled={loggingOut} onClick={logout} className="mt-2 flex w-full items-center gap-3 rounded-xl px-3 py-2.5 text-sm font-bold text-red-600 transition hover:bg-red-50 dark:hover:bg-red-500/10"><LogOut className="size-4"/>{loggingOut?"Signing out…":"Log out"}</button></div>
 </aside>
 <div className="lg:pl-[280px]"><header className="sticky top-0 z-20 flex h-20 items-center justify-end gap-3 border-b bg-canvas/85 px-5 backdrop-blur-xl lg:justify-between"><button onClick={()=>active?router.push("/dashboard/students"):setActivationOpen(true)} className="ml-12 hidden w-full max-w-md items-center gap-3 rounded-xl border bg-panel px-4 py-2.5 text-sm text-muted lg:flex"><Search className="size-4"/>Search students<kbd className="ml-auto flex gap-1 rounded border px-2 py-1 text-xs"><Command className="size-3"/>K</kbd></button><div className="relative flex items-center gap-2"><ThemeToggle/><div className="ml-2 hidden items-center gap-2 sm:flex"><span className="grid size-9 place-items-center rounded-full bg-violet-600 text-sm font-bold text-white">{initials}</span><div><b className="block text-sm">{user.name}</b><small className="capitalize text-muted">{user.role.toLowerCase().replace("_"," ")}</small></div></div></div></header><main className="p-5 sm:p-8">{children}</main></div><SubscriptionModal open={activationOpen} onClose={closeActivation} subscription={subscription} schoolName={schoolName}/></div>
}
function LayersIcon({className}:{className?:string}){return <BookOpen className={className}/>}
