"use client";
import Link from "next/link";
import { useEffect,useMemo,useState } from "react";
import { Download,Eye,FilePlus2,FileSpreadsheet,FileText,FileUp,Loader2,Printer,Search } from "lucide-react";

type Receipt={id:string;studentName:string;admission:string;className:string;section:string;invoiceNumber:string;receiptNumber:string;amount:number;method:string;transactionId:string;paymentDate:string;status:string;createdAt:string};
export function FeeReceipts(){
 const[receipts,setReceipts]=useState<Receipt[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState(""),[query,setQuery]=useState(""),[className,setClassName]=useState(""),[status,setStatus]=useState(""),[date,setDate]=useState("");
 useEffect(()=>{fetch("/api/student-payments").then(async response=>{const data=await response.json();if(!response.ok)throw new Error(data.error||"Could not load receipts.");setReceipts(data.payments||[])}).catch(reason=>setError(reason instanceof Error?reason.message:"Could not load receipts.")).finally(()=>setLoading(false))},[]);
 const classes=useMemo(()=>[...new Set(receipts.map(item=>item.className).filter(Boolean))].sort(),[receipts]),filtered=useMemo(()=>receipts.filter(item=>(item.studentName+item.admission+item.receiptNumber+item.invoiceNumber+item.transactionId).toLowerCase().includes(query.toLowerCase())&&(!className||item.className===className)&&(!status||item.status===status)&&(!date||item.paymentDate.slice(0,10)===date)),[receipts,query,className,status,date]),total=filtered.reduce((sum,item)=>sum+Number(item.amount),0),exportQuery=`search=${encodeURIComponent(query)}&class=${encodeURIComponent(className)}&status=${encodeURIComponent(status)}${date?`&from=${date}&to=${date}`:""}`;
 return <div className="mx-auto max-w-[1500px]"><div className="flex flex-col justify-between gap-4 lg:flex-row lg:items-end"><div><p className="label">Finance</p><h1 className="mt-2 text-3xl font-black sm:text-4xl">Fee Receipts</h1><p className="mt-2 text-muted">Search, preview, download and print verified student payment receipts.</p></div><div className="flex flex-wrap gap-2"><Link href="/dashboard/payments" className="btn-primary"><FilePlus2 className="size-4"/>Generate receipt</Link><Link href="/dashboard/import?type=payments" className="btn-secondary"><FileUp className="size-4"/>Import Excel / CSV</Link><Link href="/dashboard/payment-history" className="btn-secondary">Payment history</Link><a href={`/api/export?type=payments&format=xlsx&${exportQuery}`} className="btn-secondary"><FileSpreadsheet className="size-4"/>Excel</a><a href={`/api/export?type=payments&format=csv&${exportQuery}`} className="btn-secondary"><Download className="size-4"/>CSV</a></div></div>{error&&<p role="alert" className="mt-5 rounded-xl border border-red-200 bg-red-50 p-3 text-sm text-red-700">{error}</p>}
 <section className="mt-7 grid gap-3 sm:grid-cols-3"><Metric label="Verified receipts" value={String(filtered.length)}/><Metric label="Receipt value" value={new Intl.NumberFormat("en-IN",{style:"currency",currency:"INR",maximumFractionDigits:0}).format(total)}/><Metric label="Classes represented" value={String(new Set(filtered.map(item=>item.className)).size)}/></section>
 <section className="card mt-5 overflow-hidden"><div className="grid gap-3 border-b p-4 md:grid-cols-2 xl:grid-cols-5"><label className="flex items-center gap-2 rounded-xl border px-3 md:col-span-2"><Search className="size-4 text-muted"/><input value={query} onChange={event=>setQuery(event.target.value)} className="w-full bg-transparent py-2.5 text-sm outline-none" placeholder="Student, admission, receipt or transaction..."/></label><select value={className} onChange={event=>setClassName(event.target.value)} className="rounded-xl border bg-panel px-3 text-sm"><option value="">All classes</option>{classes.map(item=><option key={item}>{item}</option>)}</select><select value={status} onChange={event=>setStatus(event.target.value)} className="rounded-xl border bg-panel px-3 text-sm"><option value="">All statuses</option><option>Success</option></select><input aria-label="Payment date" type="date" value={date} onChange={event=>setDate(event.target.value)} className="rounded-xl border bg-panel px-3 text-sm"/></div>
 {loading?<div className="grid min-h-72 place-items-center"><Loader2 className="animate-spin text-brand"/></div>:<div className="overflow-x-auto"><table className="w-full whitespace-nowrap text-left text-sm"><thead className="bg-canvas text-xs uppercase text-muted"><tr>{["Receipt","Payment date","Student","Admission","Class","Amount","Method","Transaction","Status","Actions"].map(label=><th className="px-4 py-4" key={label}>{label}</th>)}</tr></thead><tbody className="divide-y">{filtered.map(item=><tr className="hover:bg-canvas/60" key={item.id}><td className="px-4 py-4 font-bold text-brand">{item.receiptNumber}</td><td className="px-4">{item.paymentDate}</td><td className="px-4 font-bold">{item.studentName}</td><td className="px-4">{item.admission}</td><td className="px-4">{item.className}-{item.section}</td><td className="px-4 font-bold">{new Intl.NumberFormat("en-IN",{style:"currency",currency:"INR"}).format(item.amount)}</td><td className="px-4">{item.method}</td><td className="px-4">{item.transactionId||"—"}</td><td className="px-4"><span className="rounded-full bg-emerald-100 px-2.5 py-1 text-xs font-bold text-emerald-700">{item.status}</span></td><td className="px-4"><div className="flex gap-1"><Link href={`/dashboard/receipts/${encodeURIComponent(item.receiptNumber)}`} className="icon-btn" title="View receipt"><Eye/></Link><a href={`/api/receipts/${encodeURIComponent(item.receiptNumber)}/pdf`} className="icon-btn" title="Download PDF"><Download/></a><Link href={`/dashboard/receipts/${encodeURIComponent(item.receiptNumber)}?print=1`} className="icon-btn" title="Print receipt"><Printer/></Link></div></td></tr>)}</tbody></table>{!filtered.length&&<div className="p-14 text-center"><FileText className="mx-auto size-9 text-muted"/><b className="mt-3 block">No receipts found</b><p className="mt-1 text-sm text-muted">Record a successful fee payment to generate a receipt automatically.</p></div>}</div>}</section></div>
}
function Metric({label,value}:{label:string;value:string}){return <article className="card p-5"><p className="text-sm text-muted">{label}</p><b className="mt-2 block text-2xl">{value}</b></article>}
