"use client";
import Link from "next/link";
import Image from "next/image";
import { useRouter } from "next/navigation";
import { useEffect,useMemo,useRef,useState,type ChangeEvent,type ReactNode } from "react";
import { Archive,Building2,CalendarDays,Check,ChevronLeft,FileText,GraduationCap,ImageIcon,Loader2,Plus,Save,Settings,Trash2,Upload,Users,X } from "lucide-react";

type Year={name:string;startMonth:number;endMonth:number;status:"Active"|"Archived";isActive?:boolean};
type SchoolClass={id?:string;name:string;active:boolean;sections:string[]};
type Data={name:string;academicYear:string;address:string;phone:string;email:string;diseCode:string;website:string;city:string;state:string;pinCode:string;principalName:string;registrationNumber:string;affiliation:string;motto:string;schoolType:string;feeReceiptTitle:string;feeReceiptSubheader:string;payslipTitle:string;payslipSubheader:string;footerText:string;signatureLabel:string;logoUrl:string;signatureUrl:string;years:Year[];classes:SchoolClass[]};
const months=["January","February","March","April","May","June","July","August","September","October","November","December"];
const defaults=["Playgroup","Pre-Nursery","Nursery","LKG","UKG",...Array.from({length:12},(_,i)=>`Class ${i+1}`)];

export function SettingsPage(){
 const router=useRouter(),savingRef=useRef(false);
 const [data,setData]=useState<Data|null>(null),[canEdit,setCanEdit]=useState(false),[saving,setSaving]=useState(false),[dirty,setDirty]=useState(false),[message,setMessage]=useState<{kind:"ok"|"error";text:string}|null>(null),[customClass,setCustomClass]=useState(""),[sectionClass,setSectionClass]=useState(""),[newSection,setNewSection]=useState(""),[newYear,setNewYear]=useState("");
 useEffect(()=>{fetch("/api/settings").then(async r=>{const j=await r.json();if(!r.ok)throw new Error(j.error);setData(j.settings);setCanEdit(j.canEdit);setSectionClass(j.settings.classes.find((x:SchoolClass)=>x.active)?.name||"")}).catch(e=>setMessage({kind:"error",text:e.message||"Unable to load settings."}))},[]);
 useEffect(()=>{const warn=(e:BeforeUnloadEvent)=>{if(dirty){e.preventDefault();e.returnValue=""}};addEventListener("beforeunload",warn);return()=>removeEventListener("beforeunload",warn)},[dirty]);
 const activeYear=useMemo(()=>data?.years.find(y=>y.name===data.academicYear),[data]);
 function patch(values:Partial<Data>){setData(current=>current?{...current,...values}:current);setDirty(true);setMessage(null)}
 function patchYear(name:string,values:Partial<Year>){if(!data)return;patch({years:data.years.map(y=>y.name===name?{...y,...values}:y)})}
 function toggleClass(name:string){if(!data)return;const found=data.classes.find(x=>x.name===name);patch({classes:found?data.classes.map(x=>x.name===name?{...x,active:!x.active}:x):[...data.classes,{name,active:true,sections:[]}]});if(!sectionClass)setSectionClass(name)}
 function addClass(){const name=customClass.trim();if(!name||data?.classes.some(x=>x.name.toLowerCase()===name.toLowerCase()))return;toggleClass(name);setCustomClass("")}
 function addSection(){const name=newSection.trim();if(!data||!name||!sectionClass)return;const target=data.classes.find(x=>x.name===sectionClass);if(!target||target.sections.some(x=>x.toLowerCase()===name.toLowerCase())){setMessage({kind:"error",text:"This section already exists for the selected class."});return}patch({classes:data.classes.map(x=>x.name===sectionClass?{...x,sections:[...x.sections,name]}:x)});setNewSection("")}
 function removeSection(name:string){if(!data)return;patch({classes:data.classes.map(x=>x.name===sectionClass?{...x,sections:x.sections.filter(s=>s!==name)}:x)})}
 function addYear(){if(!data||!/^\d{4}-\d{4}$/.test(newYear)||data.years.some(y=>y.name===newYear)){setMessage({kind:"error",text:"Enter a unique academic year in YYYY-YYYY format."});return}const start=Number(newYear.slice(0,4)),end=Number(newYear.slice(5));if(end!==start+1){setMessage({kind:"error",text:"Academic year must span consecutive years."});return}patch({years:[...data.years,{name:newYear,startMonth:4,endMonth:3,status:"Active"}]});setNewYear("")}
 async function save(){if(!data||savingRef.current||!canEdit)return;savingRef.current=true;setSaving(true);setMessage(null);const year=data.years.find(y=>y.name===data.academicYear);try{const r=await fetch("/api/settings",{method:"PUT",headers:{"Content-Type":"application/json",Accept:"application/json"},body:JSON.stringify({...data,startMonth:year?.startMonth||4,endMonth:year?.endMonth||3,academicYears:data.years.map(({name,startMonth,endMonth,status})=>({name,startMonth,endMonth,status})),classes:data.classes.filter(x=>x.active).map(({name,sections})=>({name,sections}))})}),text=await r.text();let j:{settings?:Data;error?:string}={};try{j=text?JSON.parse(text):{}}catch{throw new Error("The server returned an invalid response. Please try again.")}if(!r.ok||!j.settings)throw new Error(j.error||"Unable to save settings. Please try again.");setData(j.settings);setDirty(false);setMessage({kind:"ok",text:"Settings saved successfully!"});router.refresh()}catch(e){setMessage({kind:"error",text:e instanceof Error?e.message:"Unable to save settings. Please try again."})}finally{savingRef.current=false;setSaving(false)}}
 async function asset(kind:"logo"|"signature",file?:File){if(!file||!data)return;if(file.size>2*1024*1024){setMessage({kind:"error",text:`${kind==="logo"?"Logo":"Signature"} must be less than 2MB.`});return}const form=new FormData();form.set("file",file);const r=await fetch(`/api/settings/assets/${kind}`,{method:"PUT",body:form}),text=await r.text();let j:{url?:string;error?:string}={};try{j=text?JSON.parse(text):{}}catch{setMessage({kind:"error",text:"The upload service returned an invalid response."});return}if(!r.ok||!j.url){setMessage({kind:"error",text:j.error||"Unable to save the image."});return}setData(current=>current?{...current,[`${kind}Url`]:j.url!}:current);setMessage({kind:"ok",text:`${kind==="logo"?"Logo":"Signature"} uploaded successfully.`})}
 async function removeAsset(kind:"logo"|"signature"){const r=await fetch(`/api/settings/assets/${kind}`,{method:"DELETE"});if(!r.ok){setMessage({kind:"error",text:"Unable to remove image."});return}setData(current=>current?{...current,[`${kind}Url`]:""}:current);setMessage({kind:"ok",text:`${kind==="logo"?"Logo":"Signature"} removed successfully.`})}
 if(!data)return <div className="grid min-h-96 place-items-center">{message?<p role="alert" className="text-red-600">{message.text}</p>:<Loader2 className="animate-spin text-violet-600"/>}</div>;
 const allClasses=Array.from(new Set([...defaults,...data.classes.map(x=>x.name)])),activeClasses=data.classes.filter(x=>x.active);
 return <div className="mx-auto max-w-7xl overflow-hidden pb-10">
  <header className="mb-6 flex flex-col gap-5 sm:flex-row sm:items-start sm:justify-between"><div><Link href="/dashboard" className="mb-4 inline-flex items-center gap-1 text-sm font-semibold text-muted hover:text-violet-600"><ChevronLeft className="size-4"/>Back to dashboard</Link><div className="flex items-start gap-3"><span className="grid size-11 shrink-0 place-items-center rounded-2xl bg-violet-100 text-violet-700 dark:bg-violet-500/15"><Settings className="size-5"/></span><div><h1 className="text-2xl font-black sm:text-3xl">Institution Settings</h1><p className="mt-1 max-w-2xl text-sm text-muted">Manage academic years, classes, school details, document templates, and archives.</p></div></div></div><div className="flex flex-wrap items-center gap-2"><span className="rounded-full bg-emerald-100 px-3 py-1.5 text-xs font-bold text-emerald-700">{data.academicYear} · Active</span>{canEdit&&<a href="/api/export?type=settings&format=pdf" target="_blank" rel="noreferrer" className="settings-secondary"><FileText className="size-4"/>Settings PDF</a>}{canEdit&&<SaveButton saving={saving} onClick={save}/>}</div></header>
  {!canEdit&&<p className="mb-5 rounded-2xl border border-amber-200 bg-amber-50 p-4 text-sm font-semibold text-amber-800">You have view-only access. Only school administrators can change institution settings.</p>}
  {message&&<><p role="status" className={`mb-5 rounded-2xl border p-4 text-sm font-semibold ${message.kind==="ok"?"border-emerald-200 bg-emerald-50 text-emerald-700":"border-red-200 bg-red-50 text-red-700"}`}>{message.kind==="ok"&&<Check className="mr-2 inline size-4"/>}{message.text}</p><div aria-live="polite" className={`fixed bottom-5 right-5 z-[90] flex max-w-[calc(100vw-2.5rem)] items-center gap-2 rounded-2xl px-5 py-4 text-sm font-bold text-white shadow-2xl ${message.kind==="ok"?"bg-emerald-600":"bg-red-600"}`}>{message.kind==="ok"?<Check className="size-4"/>:<X className="size-4"/>}{message.text}</div></>}
  <fieldset disabled={!canEdit} className="space-y-6 disabled:opacity-80">
   <Card icon={<CalendarDays/>} title="Academic Year Management" description="Switch years without changing historical student, fee, payment, or finance records."><div className="grid gap-4 md:grid-cols-3"><Select label="Current academic year" value={data.academicYear} onChange={e=>patch({academicYear:e.target.value})}>{data.years.filter(y=>y.status==='Active').map(y=><option key={y.name}>{y.name}</option>)}</Select><Select label="Start month" value={activeYear?.startMonth||4} onChange={e=>patchYear(data.academicYear,{startMonth:Number(e.target.value)})}>{months.map((m,i)=><option value={i+1} key={m}>{m}</option>)}</Select><Select label="End month" value={activeYear?.endMonth||3} onChange={e=>patchYear(data.academicYear,{endMonth:Number(e.target.value)})}>{months.map((m,i)=><option value={i+1} key={m}>{m}</option>)}</Select></div><div className="mt-5 flex flex-col gap-2 sm:flex-row"><Input ariaLabel="New academic year" value={newYear} onChange={e=>setNewYear(e.target.value)} placeholder="2027-2028"/><button type="button" onClick={addYear} className="settings-secondary"><Plus className="size-4"/>Add year</button></div><div className="mt-4 grid gap-2 sm:grid-cols-2 lg:grid-cols-3">{data.years.map(y=><div key={y.name} className="flex items-center justify-between rounded-xl border bg-canvas/60 p-3"><div><b className="text-sm">{y.name}</b><p className="text-xs text-muted">{months[y.startMonth-1]} – {months[y.endMonth-1]}</p></div>{y.name===data.academicYear?<span className="text-xs font-bold text-emerald-600">Active</span>:<button type="button" onClick={()=>patchYear(y.name,{status:y.status==='Archived'?'Active':'Archived'})} className="text-xs font-bold text-muted hover:text-violet-600">{y.status==='Archived'?'Restore':'Archive'}</button>}</div>)}</div></Card>
   <Card icon={<GraduationCap/>} title="Classes Taught" description="Selected classes appear throughout admissions, students, fees, attendance, and reports."><div className="flex flex-wrap gap-2">{allClasses.map(name=>{const selected=data.classes.find(x=>x.name===name)?.active;return <button type="button" key={name} onClick={()=>toggleClass(name)} className={`rounded-xl border px-3 py-2 text-sm font-semibold transition ${selected?'border-violet-500 bg-violet-600 text-white':'bg-panel hover:border-violet-300 hover:text-violet-700'}`}>{selected&&<Check className="mr-1 inline size-3"/>}{name}</button>})}</div><div className="mt-5 flex flex-col gap-2 sm:flex-row"><Input ariaLabel="Custom class name" value={customClass} onChange={e=>setCustomClass(e.target.value)} placeholder="Add a custom class"/><button type="button" onClick={addClass} className="settings-secondary"><Plus className="size-4"/>Add class</button></div></Card>
   <Card icon={<Users/>} title="Class Sections Configuration" description="Add section names for each class. Leave empty when a class has no sections."><div className="grid gap-5 md:grid-cols-[220px_1fr]"><Select label="Select class" value={sectionClass} onChange={e=>setSectionClass(e.target.value)}>{activeClasses.map(x=><option key={x.name}>{x.name}</option>)}</Select><div><span className="settings-label">Sections for {sectionClass||"selected class"}</span><div className="mt-2 min-h-12 rounded-xl border bg-canvas/60 p-3">{data.classes.find(x=>x.name===sectionClass)?.sections.map(s=><span key={s} className="mr-2 inline-flex items-center gap-1 rounded-lg bg-violet-100 px-2.5 py-1.5 text-sm font-bold text-violet-700">{s}<button type="button" aria-label={`Remove section ${s}`} onClick={()=>removeSection(s)}><X className="size-3"/></button></span>)}{!data.classes.find(x=>x.name===sectionClass)?.sections.length&&<span className="text-sm text-muted">No sections configured</span>}</div><div className="mt-3 flex flex-col gap-2 sm:flex-row"><Input ariaLabel="New section" value={newSection} onChange={e=>setNewSection(e.target.value)} placeholder="e.g. A, B, Rose"/><button type="button" onClick={addSection} className="settings-secondary"><Plus className="size-4"/>Add section</button></div></div></div></Card>
   <Card icon={<Building2/>} title="General Information" description="These school details are available to receipts, reports, and official documents."><div className="grid gap-4 md:grid-cols-2"><Field label="School name" value={data.name} onChange={v=>patch({name:v})} required/><Field label="DISE / UDISE code" value={data.diseCode} onChange={v=>patch({diseCode:v})}/><label className="md:col-span-2"><span className="settings-label">Address</span><textarea maxLength={200} value={data.address} onChange={e=>patch({address:e.target.value})} rows={3} className="settings-input resize-y" placeholder="Enter school address"/><small className="float-right mt-1 text-xs text-muted">{data.address.length}/200</small></label><Field label="Phone" value={data.phone} onChange={v=>patch({phone:v})}/><Field label="Email" type="email" value={data.email} onChange={v=>patch({email:v})}/><Field label="Website" type="url" value={data.website} onChange={v=>patch({website:v})}/><Field label="Principal name" value={data.principalName} onChange={v=>patch({principalName:v})}/><Field label="City" value={data.city} onChange={v=>patch({city:v})}/><Field label="State" value={data.state} onChange={v=>patch({state:v})}/><Field label="PIN code" value={data.pinCode} onChange={v=>patch({pinCode:v})}/><Field label="Registration number" value={data.registrationNumber} onChange={v=>patch({registrationNumber:v})}/><Field label="Affiliation" value={data.affiliation} onChange={v=>patch({affiliation:v})}/><Field label="School type" value={data.schoolType} onChange={v=>patch({schoolType:v})}/><Field label="School motto" value={data.motto} onChange={v=>patch({motto:v})}/></div></Card>
   <div className="grid gap-6 lg:grid-cols-2"><AssetCard title="School Logo" description="Recommended 200×200px · PNG, JPG or WebP · Max 2MB" kind="logo" url={data.logoUrl} onUpload={asset} onRemove={removeAsset}/><AssetCard title="Authorized Signature" description="Transparent PNG recommended · Max 2MB" kind="signature" url={data.signatureUrl} onUpload={asset} onRemove={removeAsset}/></div>
   <Card icon={<FileText/>} title="Templates & Formats" description="Customize document text separately for this school."><div className="grid gap-4 md:grid-cols-2"><Field label="Fee receipt title" value={data.feeReceiptTitle} onChange={v=>patch({feeReceiptTitle:v})}/><Field label="Fee receipt sub-header text" value={data.feeReceiptSubheader} onChange={v=>patch({feeReceiptSubheader:v})}/><Field label="Pay slip title" value={data.payslipTitle} onChange={v=>patch({payslipTitle:v})}/><Field label="Pay slip sub-header text" value={data.payslipSubheader} onChange={v=>patch({payslipSubheader:v})}/><Field label="Authorized signature label" value={data.signatureLabel} onChange={v=>patch({signatureLabel:v})}/><Field label="Document footer text" value={data.footerText} onChange={v=>patch({footerText:v})}/></div></Card>
   <Card icon={<Archive/>} title="Student Archives" description="Archived students and their historical financial and academic records remain intact."><div className="grid gap-3 sm:grid-cols-2"><Link href="/dashboard/students?status=Left" className="settings-archive"><Archive className="size-5 text-amber-600"/><span><b>View Left Out Students</b><small>Leaving dates, reasons and profiles</small></span></Link><Link href="/dashboard/students?status=Graduated" className="settings-archive"><GraduationCap className="size-5 text-violet-600"/><span><b>View Graduated Students</b><small>Graduation details and records</small></span></Link></div></Card>
  </fieldset>
  {canEdit&&<div className="mt-7 flex flex-col items-center justify-between gap-3 rounded-3xl bg-slate-950 p-5 text-white sm:flex-row"><div><b>Ready to apply your changes?</b><p className="text-sm text-slate-300">All sections are saved together in one secure transaction.</p></div><SaveButton saving={saving} onClick={save}/></div>}
 </div>
}
function Card({icon,title,description,children}:{icon:ReactNode;title:string;description:string;children:ReactNode}){return <section className="card overflow-hidden"><div className="flex gap-3 border-b p-5 sm:p-6"><span className="mt-0.5 grid size-9 shrink-0 place-items-center rounded-xl bg-violet-100 text-violet-700 [&>svg]:size-4">{icon}</span><div><h2 className="font-extrabold">{title}</h2><p className="mt-0.5 text-sm text-muted">{description}</p></div></div><div className="p-5 sm:p-6">{children}</div></section>}
function SaveButton({saving,onClick}:{saving:boolean;onClick:()=>void}){return <button type="button" disabled={saving} onClick={onClick} className="inline-flex min-h-11 items-center justify-center gap-2 rounded-xl bg-violet-600 px-5 text-sm font-bold text-white shadow-lg shadow-violet-500/20 hover:bg-violet-700 disabled:cursor-not-allowed disabled:opacity-60">{saving?<Loader2 className="size-4 animate-spin"/>:<Save className="size-4"/>}{saving?"Saving…":"Save All Settings"}</button>}
function Field({label,value,onChange,type="text",required=false}:{label:string;value:string;onChange:(v:string)=>void;type?:string;required?:boolean}){return <label><span className="settings-label">{label}{required&&<span className="text-red-500"> *</span>}</span><input className="settings-input" type={type} value={value} onChange={e=>onChange(e.target.value)} required={required}/></label>}
function Input({ariaLabel,...props}:{ariaLabel:string;value:string;onChange:(e:ChangeEvent<HTMLInputElement>)=>void;placeholder:string}){return <input aria-label={ariaLabel} className="settings-input flex-1" {...props}/>}
function Select({label,children,...props}:{label:string;children:ReactNode;value:string|number;onChange:(e:ChangeEvent<HTMLSelectElement>)=>void}){return <label><span className="settings-label">{label}</span><select className="settings-input" {...props}>{children}</select></label>}
function AssetCard({title,description,kind,url,onUpload,onRemove}:{title:string;description:string;kind:"logo"|"signature";url:string;onUpload:(k:"logo"|"signature",f?:File)=>void;onRemove:(k:"logo"|"signature")=>void}){return <section className="card p-5 sm:p-6"><div className="flex items-center gap-3"><ImageIcon className="size-5 text-violet-600"/><div><h2 className="font-extrabold">{title}</h2><p className="text-xs text-muted">{description}</p></div></div><div className="mt-5 flex min-h-40 flex-col items-center justify-center rounded-2xl border-2 border-dashed bg-canvas/60 p-5 text-center">{url?<Image unoptimized src={url} width={160} height={96} style={{width:"auto",height:"auto"}} alt={`${title} preview`} className="mb-4 max-h-24 max-w-40 object-contain"/>:<ImageIcon className="mb-3 size-10 text-slate-300"/>}<label className="settings-secondary cursor-pointer"><Upload className="size-4"/>{url?"Replace":"Upload"} {kind==="logo"?"Logo":"Signature"}<input type="file" className="sr-only" accept="image/png,image/jpeg,image/webp" onChange={e=>onUpload(kind,e.target.files?.[0])}/></label>{url&&<button type="button" onClick={()=>onRemove(kind)} className="mt-3 inline-flex items-center gap-1 text-xs font-bold text-red-600"><Trash2 className="size-3"/>Remove</button>}</div></section>}
