ALTER TABLE settings ADD COLUMN IF NOT EXISTS dise_code TEXT NOT NULL DEFAULT '';
ALTER TABLE settings ADD COLUMN IF NOT EXISTS website TEXT NOT NULL DEFAULT '';
ALTER TABLE settings ADD COLUMN IF NOT EXISTS city TEXT NOT NULL DEFAULT '';
ALTER TABLE settings ADD COLUMN IF NOT EXISTS state TEXT NOT NULL DEFAULT '';
ALTER TABLE settings ADD COLUMN IF NOT EXISTS pin_code TEXT NOT NULL DEFAULT '';
ALTER TABLE settings ADD COLUMN IF NOT EXISTS principal_name TEXT NOT NULL DEFAULT '';
ALTER TABLE settings ADD COLUMN IF NOT EXISTS registration_number TEXT NOT NULL DEFAULT '';
ALTER TABLE settings ADD COLUMN IF NOT EXISTS affiliation TEXT NOT NULL DEFAULT '';
ALTER TABLE settings ADD COLUMN IF NOT EXISTS motto TEXT NOT NULL DEFAULT '';
ALTER TABLE settings ADD COLUMN IF NOT EXISTS school_type TEXT NOT NULL DEFAULT '';
ALTER TABLE settings ADD COLUMN IF NOT EXISTS fee_receipt_title TEXT NOT NULL DEFAULT 'Fee Payment Receipt';
ALTER TABLE settings ADD COLUMN IF NOT EXISTS fee_receipt_subheader TEXT NOT NULL DEFAULT 'Standard Fee Receipt Template';
ALTER TABLE settings ADD COLUMN IF NOT EXISTS payslip_title TEXT NOT NULL DEFAULT 'Pay Slip';
ALTER TABLE settings ADD COLUMN IF NOT EXISTS payslip_subheader TEXT NOT NULL DEFAULT 'Standard Pay Slip Template';
ALTER TABLE settings ADD COLUMN IF NOT EXISTS footer_text TEXT NOT NULL DEFAULT '';
ALTER TABLE settings ADD COLUMN IF NOT EXISTS signature_label TEXT NOT NULL DEFAULT 'Authorized Signatory';
ALTER TABLE students ADD COLUMN IF NOT EXISTS academic_year TEXT NOT NULL DEFAULT '';
ALTER TABLE students ADD COLUMN IF NOT EXISTS leaving_date TEXT;
ALTER TABLE students ADD COLUMN IF NOT EXISTS leaving_reason TEXT NOT NULL DEFAULT '';
ALTER TABLE students ADD COLUMN IF NOT EXISTS graduation_date TEXT;
CREATE TABLE IF NOT EXISTS academic_years(id TEXT PRIMARY KEY,institution_id TEXT NOT NULL REFERENCES institutions(id),name TEXT NOT NULL,start_month INTEGER NOT NULL DEFAULT 4 CHECK(start_month BETWEEN 1 AND 12),end_month INTEGER NOT NULL DEFAULT 3 CHECK(end_month BETWEEN 1 AND 12),status TEXT NOT NULL DEFAULT 'Active' CHECK(status IN ('Active','Archived')),is_active BOOLEAN NOT NULL DEFAULT FALSE,created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,UNIQUE(institution_id,name));
CREATE TABLE IF NOT EXISTS institution_classes(id TEXT PRIMARY KEY,institution_id TEXT NOT NULL REFERENCES institutions(id),name TEXT NOT NULL,sort_order INTEGER NOT NULL DEFAULT 0,status TEXT NOT NULL DEFAULT 'Active' CHECK(status IN ('Active','Inactive')),created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,UNIQUE(institution_id,name));
CREATE TABLE IF NOT EXISTS institution_sections(id TEXT PRIMARY KEY,institution_id TEXT NOT NULL REFERENCES institutions(id),class_id TEXT NOT NULL REFERENCES institution_classes(id) ON DELETE RESTRICT,name TEXT NOT NULL,sort_order INTEGER NOT NULL DEFAULT 0,status TEXT NOT NULL DEFAULT 'Active' CHECK(status IN ('Active','Inactive')),created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,UNIQUE(class_id,name));
CREATE TABLE IF NOT EXISTS school_assets(id TEXT PRIMARY KEY,institution_id TEXT NOT NULL REFERENCES institutions(id),kind TEXT NOT NULL CHECK(kind IN ('logo','signature')),mime_type TEXT NOT NULL,data BYTEA NOT NULL,size_bytes INTEGER NOT NULL,updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,UNIQUE(institution_id,kind));
CREATE INDEX IF NOT EXISTS idx_academic_years_scope ON academic_years(institution_id,status,is_active);
CREATE INDEX IF NOT EXISTS idx_institution_classes_scope ON institution_classes(institution_id,status,sort_order);
CREATE INDEX IF NOT EXISTS idx_institution_sections_scope ON institution_sections(institution_id,class_id,status,sort_order);
CREATE TABLE IF NOT EXISTS student_enrollments(id TEXT PRIMARY KEY,institution_id TEXT NOT NULL REFERENCES institutions(id),student_id TEXT NOT NULL REFERENCES students(id) ON DELETE RESTRICT,academic_year TEXT NOT NULL,class_name TEXT NOT NULL,section TEXT NOT NULL DEFAULT '',status TEXT NOT NULL DEFAULT 'Active',promoted_from_enrollment_id TEXT REFERENCES student_enrollments(id) ON DELETE SET NULL,promoted_at TIMESTAMPTZ,promoted_by TEXT REFERENCES users(id) ON DELETE SET NULL,created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,UNIQUE(institution_id,student_id,academic_year));
CREATE TABLE IF NOT EXISTS promotion_batches(id TEXT PRIMARY KEY,institution_id TEXT NOT NULL REFERENCES institutions(id),source_academic_year TEXT NOT NULL,target_academic_year TEXT NOT NULL,source_class TEXT NOT NULL,source_section TEXT NOT NULL DEFAULT '',target_class TEXT NOT NULL,target_section TEXT NOT NULL DEFAULT '',promoted_by TEXT NOT NULL REFERENCES users(id),promoted_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,status TEXT NOT NULL DEFAULT 'Completed',correction_reason TEXT);
CREATE TABLE IF NOT EXISTS promotion_items(id TEXT PRIMARY KEY,batch_id TEXT NOT NULL REFERENCES promotion_batches(id) ON DELETE RESTRICT,institution_id TEXT NOT NULL REFERENCES institutions(id),student_id TEXT NOT NULL REFERENCES students(id) ON DELETE RESTRICT,source_enrollment_id TEXT NOT NULL REFERENCES student_enrollments(id),target_enrollment_id TEXT NOT NULL REFERENCES student_enrollments(id),status TEXT NOT NULL DEFAULT 'Promoted',error_message TEXT NOT NULL DEFAULT '',created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,UNIQUE(institution_id,student_id,target_enrollment_id));
CREATE INDEX IF NOT EXISTS idx_enrollments_scope ON student_enrollments(institution_id,academic_year,class_name,section,status);
CREATE INDEX IF NOT EXISTS idx_promotion_batches_scope ON promotion_batches(institution_id,promoted_at);
CREATE INDEX IF NOT EXISTS idx_promotion_items_scope ON promotion_items(institution_id,student_id,created_at);
