ALTER TABLE subscriptions ADD COLUMN IF NOT EXISTS payment_status TEXT NOT NULL DEFAULT 'Pending';
ALTER TABLE subscriptions ADD COLUMN IF NOT EXISTS plan_type TEXT NOT NULL DEFAULT 'Yearly';
ALTER TABLE subscriptions ADD COLUMN IF NOT EXISTS currency TEXT NOT NULL DEFAULT 'INR';
ALTER TABLE subscriptions ADD COLUMN IF NOT EXISTS renewal_date TIMESTAMPTZ;
ALTER TABLE subscriptions ADD COLUMN IF NOT EXISTS auto_renew BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE subscriptions ADD COLUMN IF NOT EXISTS last_notification_sent TIMESTAMPTZ;
ALTER TABLE subscriptions ADD COLUMN IF NOT EXISTS grace_period_days INTEGER NOT NULL DEFAULT 0;
ALTER TABLE notifications ADD COLUMN IF NOT EXISTS link TEXT NOT NULL DEFAULT '';
ALTER TABLE notifications ADD COLUMN IF NOT EXISTS delivery_status TEXT NOT NULL DEFAULT 'SENT';
ALTER TABLE admin_settings ADD COLUMN IF NOT EXISTS subscription_warning_days TEXT NOT NULL DEFAULT '30,15,7,3,1,0,-1';
ALTER TABLE admin_settings ADD COLUMN IF NOT EXISTS subscription_notifications_enabled BOOLEAN NOT NULL DEFAULT TRUE;
ALTER TABLE admin_settings ADD COLUMN IF NOT EXISTS in_app_notifications_enabled BOOLEAN NOT NULL DEFAULT TRUE;
ALTER TABLE admin_settings ADD COLUMN IF NOT EXISTS email_notifications_enabled BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE admin_settings ADD COLUMN IF NOT EXISTS subscription_grace_days INTEGER NOT NULL DEFAULT 0;
UPDATE subscriptions SET payment_status=CASE WHEN status IN ('ACTIVE','EXPIRING_SOON','EXPIRED') AND razorpay_payment_id IS NOT NULL THEN 'Paid' WHEN status='FAILED' THEN 'Failed' WHEN status='REFUNDED' THEN 'Refunded' ELSE payment_status END;
CREATE TABLE IF NOT EXISTS subscription_notification_events(id TEXT PRIMARY KEY,subscription_id TEXT NOT NULL REFERENCES subscriptions(id) ON DELETE CASCADE,institution_id TEXT NOT NULL REFERENCES institutions(id),milestone TEXT NOT NULL,status TEXT NOT NULL DEFAULT 'SENT',attempts INTEGER NOT NULL DEFAULT 1,last_error TEXT NOT NULL DEFAULT '',sent_at TIMESTAMPTZ,created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,UNIQUE(subscription_id,milestone));
CREATE TABLE IF NOT EXISTS subscription_processing_logs(id TEXT PRIMARY KEY,started_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,finished_at TIMESTAMPTZ,status TEXT NOT NULL,checked_count INTEGER NOT NULL DEFAULT 0,expired_count INTEGER NOT NULL DEFAULT 0,notification_count INTEGER NOT NULL DEFAULT 0,error TEXT NOT NULL DEFAULT '');
CREATE INDEX IF NOT EXISTS idx_subscriptions_expiry ON subscriptions(status,expiry_date);
CREATE INDEX IF NOT EXISTS idx_notifications_user_read ON notifications(user_id,read_at,created_at);
